- samples/SkijaInjectSample/build.gradle
After running `./gradlew publishToMavenLocal`, _skiko-jvm-runtime-macos-x64_ will be generated, but gradle is looking for _skiko-jvm-runtime-macos_x64_
So the target should be `"${targetOs}-${targetArch}"`
Fixed #22
> Fix skiko-jvm-runtime-macos_x64 is not found by gradle

- .run/SkijaInjectSample (show long frames) .run.xml
- skiko/src/jvmMain/kotlin/org/jetbrains/skiko/FPSCounter.kt
- skiko/src/jvmMain/kotlin/org/jetbrains/skiko/SkiaLayer.kt
- skiko/src/jvmMain/kotlin/org/jetbrains/skiko/SkikoProperties.kt
- property `skiko.fps.longFrames.show` to show frames longer than display refresh rate
- replace `skiko.fps.count` by `skiko.fps.periodSeconds`
- log timestamp
- remove `skiko.fps.probability`. min/max FPS are more informative
> Rewrite FPS counting

- samples/SkijaInjectSample/src/test/kotlin/org/jetbrains/skiko/SkiaWindowTest.kt
- skiko/src/jvmMain/kotlin/org/jetbrains/skiko/PlatformOperations.kt
- skiko/src/jvmMain/kotlin/org/jetbrains/skiko/SkiaLayer.kt
- skiko/src/jvmMain/kotlin/org/jetbrains/skiko/SkiaLayerProperties.kt
- skiko/src/jvmMain/kotlin/org/jetbrains/skiko/SkiaWindow.kt
- skiko/src/jvmMain/kotlin/org/jetbrains/skiko/redrawer/LinuxOpenGLRedrawer.kt
- skiko/src/jvmMain/kotlin/org/jetbrains/skiko/redrawer/MacOsOpenGLRedrawer.kt
- skiko/src/jvmMain/kotlin/org/jetbrains/skiko/redrawer/WindowsOpenGLRedrawer.kt
Drawing without vsync is disabled, because we cannot guarantee that we will draw with high FPS and don't block drawing loop.
Even with FPS limit = 300 we can do that (when we minimize/restore window)
> Fix macOs freeze when we render very fast on resize. Disable drawing without vsync

- skiko/src/jvmMain/cpp/linux/drawlayer.cc
- skiko/src/jvmMain/cpp/windows/drawlayer.cc
- skiko/src/jvmMain/kotlin/org/jetbrains/skiko/HardwareLayer.kt
- skiko/src/jvmMain/kotlin/org/jetbrains/skiko/SkiaLayer.kt
- skiko/src/jvmMain/objectiveC/macos/drawlayer.m
```
Thread 0 Crashed:: Java: AWT-AppKit  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib          0x00007fff203b2936 __pthread_kill + 10
1   libsystem_pthread.dylib         0x00007fff203e1615 pthread_kill + 263
2   libsystem_c.dylib               0x00007fff20336411 abort + 120
3   libjvm.dylib                    0x0000000108d899bc os::abort(bool, void*, void const*) + 22
4   libjvm.dylib                    0x0000000108ecf0cd VMError::report_and_die(int, char const*, char const*, __va_list_tag*, Thread*, unsigned char*, void*, void*, char const*, int, unsigned long) + 2953
5   libjvm.dylib                    0x0000000108ece51e VMError::report_and_die(Thread*, unsigned int, unsigned char*, void*, void*, char const*, ...) + 152
6   libjvm.dylib …
```
> Fix crash when we close the window immediately after its start

- skiko/src/jvmMain/kotlin/org/jetbrains/skiko/SkiaLayer.kt
- Remove manual revalidate/redraw
We don't need them anymore, because `paint` will be called every time we change size and init layer.
It is because we changed java.awt.Canvas to javax.swing.JPanel
- fix dipose
> Some fixes after metal

- skiko/src/jvmMain/kotlin/org/jetbrains/skiko/SkiaLayer.kt
- skiko/src/jvmMain/kotlin/org/jetbrains/skiko/SkikoProperties.kt
- skiko/src/jvmMain/kotlin/org/jetbrains/skiko/redrawer/Direct3DRedrawer.kt
- skiko/src/jvmMain/kotlin/org/jetbrains/skiko/redrawer/LinuxOpenGLRedrawer.kt
- skiko/src/jvmMain/kotlin/org/jetbrains/skiko/redrawer/MacOsOpenGLRedrawer.kt
- skiko/src/jvmMain/kotlin/org/jetbrains/skiko/redrawer/MetalRedrawer.kt
- skiko/src/jvmMain/kotlin/org/jetbrains/skiko/redrawer/SoftwareRedrawer.kt
- skiko/src/jvmMain/kotlin/org/jetbrains/skiko/redrawer/WindowsOpenGLRedrawer.kt
fixes 1) and 3) in #76
also fixes slow event dispathing in Compose (it is because vsync blocked AWT thread)
> macOs, Windows. draw in a background thread

- samples/SkijaInjectSample/build.gradle.kts
- skiko/src/jvmMain/cpp/common/openglapi.cc
- skiko/src/jvmMain/cpp/windows/directXRedrawer.cc
- skiko/src/jvmMain/kotlin/org/jetbrains/skiko/OpenGLApi.kt
- skiko/src/jvmMain/kotlin/org/jetbrains/skiko/context/ContextHandler.kt
- skiko/src/jvmMain/kotlin/org/jetbrains/skiko/context/Direct3DContextHandler.kt
- skiko/src/jvmMain/kotlin/org/jetbrains/skiko/context/MetalContextHandler.kt
- skiko/src/jvmMain/kotlin/org/jetbrains/skiko/context/OpenGLContextHandler.kt
- skiko/src/jvmMain/kotlin/org/jetbrains/skiko/redrawer/Direct3DRedrawer.kt
- skiko/src/jvmMain/kotlin/org/jetbrains/skiko/redrawer/MetalRedrawer.kt
- skiko/src/jvmMain/objectiveC/macos/MetalRedrawer.mm
Getting hardware info (video card, total vram) on Metal, DirectX, OpenGL.
> Hardware info

- skiko/src/jvmMain/kotlin/org/jetbrains/skiko/SkiaLayer.kt
Disabling focus keys didn't work
Test:
```
window.layer.focusTraversalKeysEnabled = false
window.layer.addKeyListener(object : KeyAdapter() {
override fun keyPressed(event: KeyEvent) {
println("keyPressed")
}
})
```
Press Tab or Shift-Tab. Before fix there was no output in console
> Fix window.layer.focusTraversalKeysEnabled = false

- skiko/build.gradle.kts
- skiko/src/jvmMain/kotlin/org/jetbrains/skiko/Library.kt
- skiko/src/jvmTest/kotlin/org/jetbrains/skiko/SeveralClassloaders.kt
Fixes https://github.com/JetBrains/compose-jb/issues/785.
> Allow loading Skiko in more than one classloader.

- samples/SkijaInjectSample/build.gradle.kts
- samples/SkijaInjectSample/src/main/kotlin/SkijaInjectSample/App.kt
- skiko/src/jvmMain/cpp/linux/drawlayer.cc
- skiko/src/jvmMain/kotlin/org/jetbrains/skiko/Library.kt
- skiko/src/jvmMain/kotlin/org/jetbrains/skiko/PlatformOperations.kt
- skiko/src/jvmMain/kotlin/org/jetbrains/skiko/Setup.kt
Force enable dpi support on Linux. To achieve this, we must set the system property "sun.java2d.uiScale" before initializing the AWT/Swing.
> Fix linux dpi

- samples/SkiaNativeSample/build.gradle.kts
- samples/SkiaNativeSample/gradle.properties
- skiko/build.gradle.kts
- skiko/gradle.properties
- skiko/src/nativeInterop/cinterop/skia.def
Added Paragraph headers into the .def file.
Some workarounds in the .def file.
`libskshaper.a` and `libskparagraph.a` encapsulated in the klib
Moved to k/n 1.5.21-dev-329.
> Native-1.5.21-dev-329

- skiko/gradle.properties
This PR bumps Skija version to 0.93.1
Notice that both 0.93.0 and 0.93.1 are a breaking change: https://github.com/JetBrains/skija/blob/5fb057b0d17ab6ec2e5c284e56707f0527daa54a/CHANGELOG.md
It also updates Skia to m93-87e8842e8c
> Update Skija to 0.93.1

- skiko/src/commonMain/kotlin/org/jetbrains/skia/ImageFilter.kt
- skiko/src/commonMain/kotlin/org/jetbrains/skia/RuntimeEffect.kt
- skiko/src/commonMain/kotlin/org/jetbrains/skia/impl/NativePointerArray.kt
- skiko/src/commonMain/kotlin/org/jetbrains/skia/paragraph/FontCollection.kt
- skiko/src/jsMain/kotlin/org/jetbrains/skia/impl/NativePointerArray.kt
- skiko/src/jvmMain/kotlin/org/jetbrains/skia/impl/NativePointerArray.kt
- skiko/src/jvmTest/kotlin/org/jetbrains/skiko/ParagraphTest.kt
Actually, as far as I understand LongArray is the only entity we should care of, IntArray supposed to be the same as Array<Int> on js (but I might be wrong)
> Don't confuse Array<NativePointer> actual implementations with LongArray and IntArray

- skiko/src/jvmMain/kotlin/org/jetbrains/skiko/FrameLimiter.kt
- skiko/src/jvmMain/kotlin/org/jetbrains/skiko/RendezvousBroadcastChannel.kt
- skiko/src/jvmTest/kotlin/org/jetbrains/skiko/FrameLimiterTest.kt
- skiko/src/jvmTest/kotlin/org/jetbrains/skiko/RendezvousBroadcastChannelTest.kt
We run FrameLimiter in another thread in SoftwareRedrawer. So FrameLimiter should be thread-safe. It is not thread safe now.
We can run it from the Swing thread though, but probably it will be used in Compose directly, where can be multiple threads (in Application frame clock, for example)
Deadlock:
[couroutine 2] onRequest.trySend(Unit)
[couroutine 1] onRequest.receive()
[couroutine 1] onResult.getAndSet(CompletableDeferred()).complete(value)
[couroutine 2] onResult.get().await() // wait
[couroutine 1] onRequest.receive()  // wait
> Fix deadlock in FrameLimiter

- skiko/src/commonMain/kotlin/org/jetbrains/skia/paragraph/LineMetrics.kt
- skiko/src/jvmMain/cpp/common/paragraph/interop.cc
- skiko/src/jvmTest/kotlin/org/jetbrains/skiko/SkiaWindowTest.kt
Motivation for this PR: We would prefer to avoid Long where it's possible, since `kotlin.Long is not mapped to any JavaScript object, as there is no 64-bit integer number type in JavaScript. It is emulated by a Kotlin class.`
In this case (Line Metrics) Int should be sufficient. 
Also added some asserts for line metrics in `testRenderText` (jvm only). 
The tests for native and js will follow as soon as we set up rendering in tests there.
> change Long to Int in Line Metrics

- skiko/src/jvmMain/cpp/linux/redrawer.cc
- skiko/src/jvmMain/kotlin/org/jetbrains/skiko/GraphicsApi.jvm.kt
Tested on VirtualBox with Fedora/Ubuntu with 3D graphics acceleration.
> Fixed fallback and transparency support on VM linux on OpenGL.

- skiko/gradle.properties
This commit will 'enable' full hierarchical multiplatform support.
Native dependency propagation is not compatible anymore with
newer IDE versions and not maintained in the KGP
> [Gradle] Disable native dependency propagation

- skiko/src/jvmMain/kotlin/org/jetbrains/skiko/Library.kt
For people who unpack Skia to their install directory.
1. Makes signing easier (don't have to sign shared libs inside zips).
2. Avoids littering the user's home directory.
3. Faster startup.
> Look for the skiko libraries in the JVM library directory first

- skiko/src/commonMain/kotlin/org/jetbrains/skia/Expects.kt
- skiko/src/commonMain/kotlin/org/jetbrains/skia/FontFeature.kt
- skiko/src/commonMain/kotlin/org/jetbrains/skia/FontVariation.kt
- skiko/src/commonTest/kotlin/org/jetbrains/skia/PatternMatcherTests.kt
- skiko/src/jsMain/kotlin/org/jetbrains/skia/Actuals.js.kt
- skiko/src/nativeMain/kotlin/org/jetbrains/skia/Actuals.native.kt
Update FontFeature.kt and FontVariation.kt parse functions to use regex numeric groups instead of named groups because [k/n doesn't support named groups](https://youtrack.jetbrains.com/issue/KT-41890)
> add Pattern and Matcher actual implementation for js and native

- skiko/src/commonMain/kotlin/org/jetbrains/skia/impl/Native.kt
- skiko/src/commonTest/kotlin/org/jetbrains/skia/impl/InteropScopeCommonTests.kt
- skiko/src/commonTest/kotlin/org/jetbrains/skiko/tests/TestHelpers.kt
- skiko/src/jsMain/kotlin/org/jetbrains/skia/impl/Native.js.kt
- skiko/src/jvmMain/kotlin/org/jetbrains/skia/impl/Native.jvm.kt
- skiko/src/jvmTest/cpp/TestHelpers.cc
- skiko/src/nativeJsTest/cpp/TestHelpers.cc
- skiko/src/nativeMain/kotlin/org/jetbrains/skia/impl/Native.native.kt
`fun toInteropForArraysOfPointers(interopPointers: Array<InteropPointer>): InteropPointer` 
This fun will be useful for example in `ShapingOptions.kt` to pass `Array<FontFeature>` to interop where FontFeature itself is going to be presented as IntArray.
> add `toInterop()` for arrays of InteropPointer

- skiko/src/commonMain/kotlin/org/jetbrains/skia/ManagedString.kt
- skiko/src/commonTest/kotlin/org/jetbrains/skia/ManagedStringTest.kt
- skiko/src/nativeJsMain/cpp/ManagedString.cc
the previous variant didn't crash, but the resulting SkString was invalid.
> use ManagedString._nMake from toInterop(String)

- skiko/src/commonMain/kotlin/org/jetbrains/skia/AnimationFrameInfo.kt
- skiko/src/commonMain/kotlin/org/jetbrains/skia/Matrix44.kt
- skiko/src/commonMain/kotlin/org/jetbrains/skia/PathSegmentIterator.kt
- skiko/src/commonMain/kotlin/org/jetbrains/skia/Point.kt
- skiko/src/commonMain/kotlin/org/jetbrains/skia/RRect.kt
- skiko/src/commonMain/kotlin/org/jetbrains/skia/Rect.kt
- skiko/src/commonMain/kotlin/org/jetbrains/skia/impl/Native.kt
- skiko/src/commonMain/kotlin/org/jetbrains/skia/svg/SVGLength.kt
- skiko/src/commonMain/kotlin/org/jetbrains/skia/svg/SVGPreserveAspectRatio.kt
Otherwise we have to write things like:
```
withResult(ShortArray(uni.size)) {
Typeface_nGetUTF32Glyphs(_ptr, interopScope { toInterop(uni) }, uni.size, it)
}
```
Which can be error-prone and actualy misleading (because we shouldn't wrap separate params ito nteropScope - this works by accident.
> withResult functions accept InteropScopeContext functions

- skiko/src/commonTest/kotlin/org/jetbrains/skia/PathMeasureTest.kt
- skiko/src/commonTest/kotlin/org/jetbrains/skia/SvgTest.kt
- skiko/src/commonTest/kotlin/org/jetbrains/skia/TextBlobTest.kt
- skiko/src/commonTest/kotlin/org/jetbrains/skia/util/assertCloseEnough.kt
This PR exists for achieving following goals:
1) clearer API for the assertCloseEnough* family of test assertions (no nullables in assertion itself)
2) smaller default EPSILON for non-js platforms
3) support for any iterables - sometimes it's just more convenient (among other things) to compare any arbitrary iterables (lists etc. - in need this in a different branch)
> Assert close enough refactoring

- skiko/src/jvmMain/kotlin/org/jetbrains/skiko/PlatformOperations.kt
- skiko/src/jvmMain/kotlin/org/jetbrains/skiko/SkiaLayer.jvm.kt
- fixed case where fullscreen mode is set before the window becomes visible and nothing happens after it becomes visible
see: https://github.com/JetBrains/compose-jb/issues/1134
> Fix fullscreen mode on macos.

- skiko/src/commonTest/kotlin/org/jetbrains/skia/ParagraphTest.kt
- skiko/src/jvmMain/cpp/common/paragraph/Paragraph.cc
- skiko/src/nativeJsMain/cpp/paragraph/Paragraph.cc
Fixes https://github.com/JetBrains/compose-jb/issues/1308
> Fix paragraph.getRectsForRange crash on Windows

- skiko/src/commonTest/kotlin/org/jetbrains/skia/ParagraphTest.kt
- skiko/src/jvmMain/cpp/common/paragraph/Paragraph.cc
The previous fix was wrong, we don't fill all indices of the array
Fixes https://github.com/JetBrains/compose-jb/issues/1308#issuecomment-981139635
> Fix getRectsForRange (attempt 2)

- skiko/build.gradle.kts
- skiko/buildSrc/src/main/kotlin/properties.kt
Customizing native publication's names does not work,
when a target cannot be compiled on a host.
A customization might lead to the inconsistent behavior,
when a kotlin multiplatform publication contains
different artifacts names, depending on a host system.
E.g. customization breaks macOS artifacts links,
if a kotlin multiplatform publication is built on Linux.
https://youtrack.jetbrains.com/issue/KT-50001
> Revert customizing native artifacts coordinates

- skiko/src/jsMain/kotlin/org/jetbrains/skiko/CanvasRenderer.kt
It makes canvas to not accumulate previous effects (e.g. scale).
Also, it makes canvas' state consistent with other platforms.
> js: resetMatrix on canvas before drawing a frame

- skiko/src/awtMain/kotlin/org/jetbrains/skiko/redrawer/LinuxOpenGLRedrawer.kt
- skiko/src/awtMain/kotlin/org/jetbrains/skiko/redrawer/MetalRedrawer.kt
- skiko/src/awtMain/kotlin/org/jetbrains/skiko/redrawer/WindowsOpenGLRedrawer.kt
- skiko/src/jvmMain/kotlin/org/jetbrains/skiko/redrawer/Direct3DRedrawer.kt
issue: https://github.com/JetBrains/compose-jb/issues/1267
> Fixed crash when [redrawImmediately] invoked while fallback process.

- samples/SkiaMultiplatformSample/src/iosMain/kotlin/org/jetbrains/skiko/sample/App.ios.kt
- skiko/src/iosMain/kotlin/org/jetbrains/skiko/SkiaLayer.ios.kt
- skiko/src/iosMain/kotlin/org/jetbrains/skiko/SkikoViewController.kt
Reason: adding gesture listeners prevents raw touch events from being used
Apple Doc https://developer.apple.com/documentation/uikit/uigesturerecognizer?language=objc:
```
If the gesture recognizer subsequently recognizes its gesture,
the touches are cancelled (in a touchesCancelled:withEvent: message).
```
> Added feature to define particular gestures to be used in UIView.

- skiko/buildSrc/src/main/kotlin/CompileSkikoCppTask.kt
```
> SVGCanvas.cc
> C:/tools/x64/jdk11.0.12_7/include\jni.h(39): fatal error C1083: Cannot open include file: 'stdio.h': No such file or directory
```
This change was for Android. Android can't build on Windows for now, will fix it later.
We probably need to check targetOs and replace slash inside https://github.com/JetBrains/skiko/blob/eaf6793bc672dd4cf357b5a0adef26585fd9c712/skiko/buildSrc/src/main/kotlin/internal/utils/ArgBuilder.kt#L79, not here
> Fix Windows build

- skiko/src/jvmMain/cpp/linux/drawlayer.cc
- skiko/src/jvmMain/cpp/windows/drawlayer.cc
- skiko/src/jvmMain/objectiveC/macos/Drawlayer.mm
This is a pretty dumb fix for https://github.com/JetBrains/compose-jb/issues/1761.
The bug was caused by 242bf304 since `SystemTheme.jvm.kt` was renamed to `SystemTheme.awt.kt` and the corresponding native functions were not updated.
> Fixed `getCurrentSystemTheme` throwing UnsatisfiedLinkError

- skiko/src/commonMain/kotlin/org/jetbrains/skia/impl/Native.kt
- skiko/src/jsMain/kotlin/org/jetbrains/skia/impl/Native.js.kt
- skiko/src/jvmMain/kotlin/org/jetbrains/skia/impl/Native.jvm.kt
- skiko/src/nativeMain/kotlin/org/jetbrains/skia/impl/Native.native.kt
Introduce `toInteropForResult` to distinguish between cases when arrays need to be copied to wasm and when not. 
native and jvm implementation delegate to `toInterop`.
> refactor `toInterop` to avoid unnecessary array copies in js when used within `withResult`

- skiko/src/awtMain/kotlin/org/jetbrains/skiko/Convertors.jvm.kt
- skiko/src/commonMain/kotlin/org/jetbrains/skiko/Events.kt
- skiko/src/jsMain/kotlin/org/jetbrains/skiko/Convertors.js.kt
- skiko/src/jsMain/kotlin/org/jetbrains/skiko/SkiaLayer.js.kt
- skiko/src/macosMain/kotlin/org/jetbrains/skiko/Convertors.macos.kt
issue: Nearly half of all clicks isn't handled when the Tap to click feature is activated on Mac (see the video attached). OS: macOS Monterey 12.0.1 (21A559).
see: https://youtrack.jetbrains.com/issue/COMPOSE-36
- added [pressedButtons] to SkikoPointerEvent to monitoring current pressed state of mouse buttons
- added [button] to SkikoPointerEvent - current button triggering mouse event
> Fixed a case where [event.modifiersEx] does not provide info about the pressed mouse button when using touchpad on MacOS 12 (AWT).

- skiko/src/awtMain/kotlin/org/jetbrains/skiko/SkiaLayer.awt.kt
To disable VRR support, we create a transparent `JPanel` with size (1, 1) and add it on top of the `SkiaLayer`. This causes mixed rendering technologies (java2d and OpenGL/DirectX) to work simultaneously in the same window and VRR cannot be enabled.
see:
- https://github.com/JetBrains/compose-jb/issues/1648
- https://youtrack.jetbrains.com/issue/TBX-6507#focus=Comments-27-5482439.0-0
> Fixed case when user get low refresh rate with VRR capable display.

- skiko/src/awtMain/kotlin/org/jetbrains/skiko/SkiaLayer.awt.kt
Reverts JetBrains/skiko#475
Window tests fail with this changes. Need a better solution.
> Revert "Fixed case when user get low refresh rate with VRR capable display."

- skiko/src/jsMain/kotlin/org/jetbrains/skia/impl/Native.js.kt
@olonho what do you think? 
it's for k/js only.
It seems that InteropScope() doesn't need to instantiated every time. Even though it's a small object, we can save a bit considering we use `interopScope {}` quite often.
> reuse InteropScope instance in k/js when using interopScope {}

- skiko/src/commonMain/kotlin/org/jetbrains/skia/shaper/Shaper.kt
ensure ManageString instance is not collected by GC before using _ptr in native calls.
> fix Shaper functions 

- .github/workflows/ci.yml
- skiko/build.gradle.kts
- skiko/buildSrc/src/main/kotlin/pkgConfigTool.kt
- skiko/docker/linux-amd64/Dockerfile
- skiko/docker/linux-arm64/Dockerfile
- skiko/docker/linux-emscripten-amd64/Dockerfile
- skiko/src/jvmMain/cpp/linux/drawlayer.cc
- skiko/src/jvmMain/cpp/linux/theme.cc
This PR adds implementation for Linux System Theme (#403)
Resources
- [Provide a standard dark style preference key in the settings portal](https://github.com/flatpak/xdg-desktop-portal/issues/629)
- [Elementary article](https://blog.elementary.io/the-need-for-a-freedesktop-dark-style-preference/)
- [Gnome 42 Dark Style Preference](https://blogs.gnome.org/alexm/2021/10/04/dark-style-preference/)
- [KDE Plasma 5.24 adds this new standard](https://kde.org/announcements/plasma/5/5.24.0/)
- [KDE implementation](https://invent.kde.org/plasma/xdg-desktop-portal-kde/-/merge_requests/49)
- [Elementary implementation](https://github.com/elementary/settings-daemon/pull/38)
This is the most Multi Desktop Environment approach so far with a non hacky way (like checking if the GTK theme end with …
> Support linux system theme

- skiko/src/jvmMain/kotlin/org/jetbrains/skiko/SkikoProperties.kt
see: https://github.com/JetBrains/skiko/issues/493
> Throw an exception if the user tries to create a SkiaLayer with an inappropriate [renderApi] on the current OS.

- skiko/build.gradle.kts
- skiko/src/awtMain/kotlin/org/jetbrains/skiko/HardwareLayer.kt
- skiko/src/awtMain/kotlin/org/jetbrains/skiko/MainUIDispatcher.awt.kt
- skiko/src/awtMain/kotlin/org/jetbrains/skiko/redrawer/AbstractDirectSoftwareRedrawer.kt
- skiko/src/awtMain/kotlin/org/jetbrains/skiko/redrawer/AngleRedrawer.kt
- skiko/src/awtMain/kotlin/org/jetbrains/skiko/redrawer/MainUIDispatcher.awt.kt
- skiko/src/awtMain/kotlin/org/jetbrains/skiko/redrawer/SoftwareRedrawer.kt
- skiko/src/jvmTest/kotlin/org/jetbrains/skiko/util/UiTest.kt
Because it overrides Dispatchers.Main
Fixes https://github.com/JetBrains/compose-jb/issues/1943 on skiko side
> Don't depend on kotlinx-coroutines-swing

- skiko/src/macosMain/kotlin/org/jetbrains/skiko/Actuals.macos.kt
https://developer.apple.com/documentation/appkit/nspasteboard/1533599-clearcontents
Current `ClipboardManager` for macOS target is unable to write to the clipboard. It seems `clearContents`  is required to run first or `setString` function will fail otherwise.
> Fix ClipboardManager unable to setText on macOS

- skiko/src/commonMain/kotlin/org/jetbrains/skia/RuntimeShaderBuilder.kt
- skiko/src/commonTest/kotlin/org/jetbrains/skia/ImageFilterTest.kt
- skiko/src/jvmMain/cpp/common/RuntimeShaderBuilder.cc
- skiko/src/nativeJsMain/cpp/RuntimeShaderBuilder.cc
For `SkShader` and `SkColorFilter` that can be passed as uniforms into the main SkSL shader
> Add bindings for SkRuntimeShaderBuilder::child

- skiko/src/commonMain/kotlin/org/jetbrains/skia/paragraph/StrutStyle.kt
- skiko/src/commonMain/kotlin/org/jetbrains/skia/paragraph/TextStyle.kt
- skiko/src/jvmMain/cpp/common/paragraph/StrutStyle.cc
- skiko/src/jvmMain/cpp/common/paragraph/TextStyle.cc
- skiko/src/nativeJsMain/cpp/paragraph/StrutStyle.cc
- skiko/src/nativeJsMain/cpp/paragraph/TextStyle.cc
This will allow us to create vertically centered text with custom line height
We need it in Fleet to get rid of our custom leading that we are currently applying around the actual lines of text. We can't leave it up to the Paragraph API right now because without the half leading feature, the additional space will not be evenly distributed above and below the text, but instead proportionally to the ascent and descent in the font. This leaves the text vertically uncentered, which is especially notable when there is a selection or a highlight behind it.
I already tested the new bindings locally with Fleet.
(cherry picked from commit f6f5338c1239625dd3ddf0e3b0e56b393e8a43ae)
> Add bindings for half leading to TextStyle and StrutStyle

- skiko/src/commonMain/kotlin/org/jetbrains/skiko/Expects.kt
It is already public in the targets
> Remove internal from org.jetbrains.skiko.currentNanoTime

- skiko/src/commonMain/kotlin/org/jetbrains/skia/Image.kt
- skiko/src/jvmMain/cpp/common/Image.cc
this makes jvm crash
```kotlin
Image.makeFromEncoded(null)
```
it should return 0 when input byte array is null
at https://github.com/JetBrains/skiko/blob/master/skiko/src/jvmMain/cpp/common/Image.cc#L48
```cpp
extern "C" JNIEXPORT jlong JNICALL Java_org_jetbrains_skia_ImageKt__1nMakeFromEncoded
(JNIEnv* env, jclass jclass, jbyteArray encodedArray, jint encodedLen) {
jbyte* encoded = env->GetByteArrayElements(encodedArray, 0);
sk_sp<SkData> encodedData = SkData::MakeWithCopy(encoded, encodedLen);
env->ReleaseByteArrayElements(encodedArray, encoded, 0);
sk_sp<SkImage> image = SkImage::MakeFromEncoded(encodedData);
return reinterpret_cast<jlong>(image.release());
}
```
crash log
```
#
#
#
#
#
#
---------------  T H R E A D  ---------------
Current thread (0x00007f5600027430):  JavaThread …
```
> `Image.makeFromEncoded()` makes jvm crash

- skiko/src/jvmMain/cpp/windows/drawlayer.cc
Closes #540
Converting `GetDpiForMonitor` gives compatibility with Windows 8.1/2012R2 and `GetDpiForWindow` theoretically goes back to Windows 7, as supported by skia.
Tested on Windows: 10, Server 2012R2, Server 2012R1.
(I don't beg for an official support for those older versions, but since this little is required to make it work I think it's nice to have, especially since it is an requirement for me and I'd like to avoid keeping my own fork of skiko).
> Dynamically load GetDpiForWindow/Monitor to support Windows before 10

- skiko/build.gradle.kts
Kotlin 1.7.0 introduced some changes related to kjs module names (affecting modules consuming skiko).
Therefore, we need to override the moduleName to avoid name collision with a different skiko.js file
> set moduleName for kjs target

- .github/workflows/ci.yml
- skiko/src/commonMain/kotlin/org/jetbrains/skia/FontFeature.kt
- skiko/src/commonTest/kotlin/org/jetbrains/skia/PatternMatcherTests.kt
Needed for Compose. I compared it with Android, and Android/Compose by documentation uses this format without quotes: ttps://www.w3.org/TR/css-fonts-3/#font-feature-settings-prop
[Compose PR](https://github.com/JetBrains/androidx/pull/251)
> Another method to parse font features

- skiko/src/awtMain/kotlin/org/jetbrains/skiko/SkiaLayer.awt.kt
- skiko/src/awtMain/kotlin/org/jetbrains/skiko/redrawer/Direct3DRedrawer.kt
- skiko/src/awtMain/kotlin/org/jetbrains/skiko/redrawer/MetalRedrawer.kt
- skiko/src/commonMain/kotlin/org/jetbrains/skiko/FPSCounter.kt
- skiko/src/commonMain/kotlin/org/jetbrains/skiko/GraphicsApi.kt
- skiko/src/jvmMain/kotlin/org/jetbrains/skiko/SkiaLayerProperties.kt
- skiko/src/jvmMain/kotlin/org/jetbrains/skiko/SkikoProperties.kt
- Make SkikoProperties public, and don't cache the values, so users can change properties in runtime
- Deprecate skiko.directx.gpu.priority and skiko.directx.gpu.priority, introduce skiko.gpu.priority. There is no need in separate priority for macOs/DirectX
- Fix skiko.fps.enabled property
> Refactor Skiko properties

- .github/workflows/ci.yml
- skiko/build.gradle.kts
- skiko/src/androidMain/kotlin/org/jetbrains/skiko/Actuals.android.kt
- skiko/src/awtMain/kotlin/org/jetbrains/skiko/Actuals.awt.kt
- skiko/src/awtMain/kotlin/org/jetbrains/skiko/SkiaLayer.awt.kt
- skiko/src/awtMain/kotlin/org/jetbrains/skiko/context/MetalContextHandler.kt
- skiko/src/awtMain/kotlin/org/jetbrains/skiko/redrawer/AWTRedrawer.kt
- skiko/src/awtMain/kotlin/org/jetbrains/skiko/redrawer/AbstractDirectSoftwareRedrawer.kt
- skiko/src/awtMain/kotlin/org/jetbrains/skiko/redrawer/Direct3DRedrawer.kt
- skiko/src/awtMain/kotlin/org/jetbrains/skiko/redrawer/LinuxOpenGLRedrawer.kt
- skiko/src/awtMain/kotlin/org/jetbrains/skiko/redrawer/LinuxSoftwareRedrawer.kt
- skiko/src/awtMain/kotlin/org/jetbrains/skiko/redrawer/MetalRedrawer.kt
- skiko/src/awtMain/kotlin/org/jetbrains/skiko/redrawer/SoftwareRedrawer.kt
- skiko/src/awtMain/kotlin/org/jetbrains/skiko/redrawer/WindowsOpenGLRedrawer.kt
- skiko/src/awtMain/kotlin/org/jetbrains/skiko/redrawer/WindowsSoftwareRedrawer.kt
- skiko/src/commonMain/kotlin/org/jetbrains/skiko/Annotations.kt
- skiko/src/commonMain/kotlin/org/jetbrains/skiko/SkiaLayerAnalytics.kt
- skiko/src/jvmMain/cpp/windows/directXRedrawer.cc
- skiko/src/jvmMain/cpp/windows/exceptions_handler.cc
- skiko/src/jvmMain/kotlin/org/jetbrains/skiko/GraphicsApi.jvm.kt
- skiko/src/jvmMain/kotlin/org/jetbrains/skiko/RenderFactory.kt
- skiko/src/jvmMain/objectiveC/macos/MetalRedrawer.mm
- skiko/src/jvmTest/kotlin/org/jetbrains/skiko/SkiaLayerPerformanceTest.kt
- skiko/src/jvmTest/kotlin/org/jetbrains/skiko/SkiaLayerTest.kt
- skiko/src/jvmTest/kotlin/org/jetbrains/skiko/util/UiTest.kt
It will help us to detect GPU's, on which we have crashes. After we compare two events, and if in the second event we have less hits, it means we have a crash. We can investigate it, and if the issue only in GPU, we will add it to not-supported-adapter.list
The plan to integrate this analytics to Toolbox.
> SkiaLayerAnalytics - send events for different steps of rendering

- skiko/build.gradle.kts
https://docs.microsoft.com/en-us/cpp/build/reference/fs-force-synchronous-pdb-writes
It was suggested by the error message in a Teamcity build
> Add /FS flag for compileJvmBindings for windows targets

- skiko/build.gradle.kts
Debug build failure for windows in Teamcity:
```
Successfully started process 'command 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\link.exe''
Creating library Z:\\BuildAgent\\work\\a64d3aa477d12f6b\\skiko\\build\\out\\link\\Debug-windows-x64\\skiko-windows-x64.lib and object Z:\\BuildAgent\\work\\a64d3aa477d12f6b\\skiko\\build\\out\\link\\Debug-windows-x64\\skiko-windows-x64.exp
skia.lib(gpu.GrD3DGpu.obj) : error LNK2019:  ----> unresolved external symbol DXGIGetDebugInterface1 <----     referenced in function "private: __cdecl GrD3DGpu::GrD3DGpu(class GrDirectContext *,struct GrContextOptions const &,struct GrD3DBackendContext const &,class sk_sp<class GrD3DMemoryAllocator>)" …
```
> add dxgi.lib for windows linkJvmBindings

- skiko/build.gradle.kts
From skia sources:
DXGIGetDebugInterface1 is defined in dxgi.lib.
But this API is tagged as a development-only capability which implies that linking to this function will cause the application to fail Windows store certification
> add dxgi.lib only for DEBUG build

- skiko/src/awtMain/kotlin/org/jetbrains/skiko/Actuals.awt.kt
Sometimes, internal AWT implementation can't properly parse the clipboard data.
getData's docs say that it can throw IOException
Fixes https://github.com/JetBrains/compose-jb/issues/2098
> Fix getting text from clipboard

- skiko/src/awtMain/kotlin/org/jetbrains/skiko/Actuals.awt.kt
We need to also catch IllegalStateException. It is said in the JavaDoc and mentioned here:
https://github.com/JetBrains/compose-jb/issues/2098#issuecomment-1234693644
> Fix clipboard

- skiko/src/awtMain/cpp/include/exceptions_handler.h
- skiko/src/awtMain/cpp/windows/SoftwareRedrawer.cc
- skiko/src/awtMain/cpp/windows/direct3DContext.cc
- skiko/src/awtMain/cpp/windows/directXRedrawer.cc
- skiko/src/awtMain/cpp/windows/exceptions_handler.cc
- skiko/src/awtMain/cpp/windows/openGLRedrawer.cc
This was enabled in Toolbox, and it seems work without issues.
When we throw RenderException, we fallback to the next render API.
> Throw a java exception on native crash by default (Windows, Linux)

- skiko/src/commonMain/kotlin/org/jetbrains/skia/Surface.kt
- skiko/src/jvmMain/cpp/common/Surface.cc
- skiko/src/nativeJsMain/cpp/Surface.cc
Question: why is SamplingMode mode being packed as two ints instead of one long?
> Add binding for SkSurface::draw() that takes sampling parameter

- skiko/gradle.properties
m105-305b7c02-1 contains a workaround for `get glyph position` method (for \r\n eol cases)
> update skia version to m105-305b7c02-1

- skiko/build.gradle.kts
- skiko/buildSrc/src/main/kotlin/properties.kt
Previously, `skiko-awt.jar` and all of `skiko-awt-runtime-*.jar` files contained the same bytecode. However, this led to duplication of bytecode in Compose projects:
* `skiko-awt.jar` is a necessary API dependency of Compose/Desktop, which means it is a runtime dependency as well;
* `skiko-awt-runtime-*.jar` is a necessary RUNTIME dependency of any Compose/Desktop project.
Thus, both `skiko-awt.jar` and `skiko-awt-runtime-*.jar` ended up in a runtime classpath of any Compose/Desktop project, so the same classes were present in the runtime classpath twice. This increased a final application image by approximately 1.1 Mb. Also, it led to excessive ProGuard warnings, e.g. https://github.com/JetBrains/compose-jb/issues/2393
This change excludes bytecode from `skiko-awt-runtime-*.jar` …
> Exclude bytecode from skiko-awt-runtime-*.jar files

- samples/SkiaAwtSample/src/main/kotlin/SkiaAwtSample/App.kt
- skiko/build.gradle.kts
- skiko/buildSrc/src/main/kotlin/properties.kt
- skiko/buildSrc/src/main/kotlin/windowsSdkPaths.kt
- skiko/gradle.properties
- skiko/gradle/wrapper/gradle-wrapper.properties
- skiko/src/jvmMain/kotlin/org/jetbrains/skiko/SkikoProperties.kt
fixes https://github.com/JetBrains/skiko/issues/607
- add `skia.arch` Gradle property. We set it to `arm64` on CI to build a version for Windows ARM
- change renderAPI fallback strategy (OpenGL doesn't work properly in Skia on Windows ARM)
> Windows ARM support

- skiko/src/commonMain/kotlin/org/jetbrains/skia/BackendRenderTarget.kt
- skiko/src/commonMain/kotlin/org/jetbrains/skia/Bitmap.kt
- skiko/src/commonMain/kotlin/org/jetbrains/skia/Canvas.kt
- skiko/src/commonMain/kotlin/org/jetbrains/skia/ColorSpace.kt
- skiko/src/commonMain/kotlin/org/jetbrains/skia/DirectContext.kt
- skiko/src/commonMain/kotlin/org/jetbrains/skia/Font.kt
- skiko/src/commonMain/kotlin/org/jetbrains/skia/FontMgr.kt
- skiko/src/commonMain/kotlin/org/jetbrains/skia/ImageFilter.kt
- skiko/src/commonMain/kotlin/org/jetbrains/skia/RuntimeEffect.kt
- skiko/src/commonMain/kotlin/org/jetbrains/skia/Surface.kt
- skiko/src/commonMain/kotlin/org/jetbrains/skia/Typeface.kt
- skiko/src/commonMain/kotlin/org/jetbrains/skia/paragraph/FontCollection.kt
- skiko/src/commonMain/kotlin/org/jetbrains/skia/paragraph/Paragraph.kt
- skiko/src/commonMain/kotlin/org/jetbrains/skia/paragraph/ParagraphBuilder.kt
- skiko/src/commonMain/kotlin/org/jetbrains/skia/paragraph/ParagraphCache.kt
- skiko/src/commonMain/kotlin/org/jetbrains/skia/paragraph/StrutStyle.kt
- skiko/src/commonMain/kotlin/org/jetbrains/skia/paragraph/TextStyle.kt
- skiko/src/commonTest/kotlin/org/jetbrains/skia/BitmapTest.kt
- skiko/src/commonTest/kotlin/org/jetbrains/skia/CanvasTest.kt
- skiko/src/jvmMain/cpp/common/Bitmap.cc
- skiko/src/jvmMain/cpp/common/paragraph/TextStyle.cc
- skiko/src/nativeJsMain/cpp/Bitmap.cc
- skiko/src/nativeJsMain/cpp/Picture.cc
- skiko/src/nativeJsMain/cpp/Typeface.cc
- skiko/src/nativeJsMain/cpp/paragraph/TextStyle.cc
- skiko/src/nativeMain/kotlin/org/jetbrains/skia/impl/RefCnt.native.kt
Kotlin/C bridges synchronisation:
Removed Kotlin parameters (like kotlin.String) from skia bridges (would not work for js)
Fixed invalid int_64t result return from bridge (would not work for emscripten)
Added/removed missing arguments from bridges
Fixed invalid named bridge
> Fix skiko declaration bridges

- .github/workflows/ci.yml
- split a big bash script into separate scripts
- add timeout-minutes: 25 to :skiko:awtTest
We decided to not include bash script to print jstack.
But I want to save it in this PR for the history (or future usage):
```bash
printJstackInBackground() {
while [ 0 ]
do
sleep 60
echo "--------------------------------------------------------------------------"
echo "--------------------------jstack result:----------------------------------"
echo "ps aux | grep java, result:"
ps aux | grep java
ps aux | grep java | grep jdk -i | awk '{print $2}' | while read pid; do
jstack $pid
done
echo "--------------------------------------------------------------------------"
done
}
printJstackInBackground &
```
> Linux AWT test - fail fast

- skiko/src/awtMain/kotlin/org/jetbrains/skiko/Display.kt
- skiko/src/awtMain/kotlin/org/jetbrains/skiko/HardwareLayer.kt
- skiko/src/awtMain/kotlin/org/jetbrains/skiko/redrawer/AbstractDirectSoftwareRedrawer.kt
- skiko/src/awtMain/kotlin/org/jetbrains/skiko/redrawer/LinuxOpenGLRedrawer.kt
- skiko/src/awtMain/kotlin/org/jetbrains/skiko/redrawer/SoftwareRedrawer.kt
- skiko/src/jvmMain/kotlin/org/jetbrains/skiko/FrameLimiter.kt
Deadlock:
[AWTThread] awtLock -> SkiaLayer.dispose -> LinuxOpenGLRedrawer.dispose -> we are here -> lockLinuxDrawingSurface -> awtLock [refreshRate updater thread] -> lockLinuxDrawingSurface -> we are here -> awtLock
We moved refreshRate to another thread, and check it only once a second, because it is not fast. I mistakenly thought in the past, that it is very slow on Linux (2ms), but it appears it was because of the awtLock itself. In the AWT thread it take 0.2ms, that is also slow for just one functions, but bearable, if it called only once every second.
Alternative is to subscribe to the native XRRScreenChangeNotifyEvent: https://www.x.org/releases/current/doc/man/man3/Xrandr.3.xhtml. But it seems X window system can have only one event queue associated with the window, and we already …
> Linux. Fix deadlock when we close a window

- skiko/buildSrc/settings.gradle.kts
- skiko/gradle/wrapper/gradle-wrapper.properties
- skiko/settings.gradle.kts
Add mavenCentral to make it not redirect to jcenter to download the dependencies (fails when running in teamcity with MacOs X86_64 agents, but ok with all other agents).
> Update gradle to 7.6 and repositories

- skiko/src/commonMain/kotlin/org/jetbrains/skia/Font.kt
For our project we needed to to use bitmaps in fonts, but this method wasn't bound. We had to use reflection in order to access it. We would like to have this method available as public API.
> Add setBitmapsEmbedded

- .github/workflows/ci.yml
- skiko/build.gradle.kts
CI was failed on platform name "android-33-ext4". Because of "33-ext4" fails to cast toInt(). Now it is fixed.
> Fix GitHub Actions Linux mavenLocal test with Android step

- skiko/src/androidMain/kotlin/org/jetbrains/skiko/Actuals.android.kt
- skiko/src/awtMain/kotlin/org/jetbrains/skiko/Actuals.awt.kt
- skiko/src/commonMain/kotlin/org/jetbrains/skiko/Platform.kt
- skiko/src/iosMain/kotlin/org/jetbrains/skiko/Actuals.ios.kt
- skiko/src/jsMain/kotlin/org/jetbrains/skiko/Actuals.js.kt
- skiko/src/linuxMain/kotlin/org/jetbrains/skiko/Actuals.linux.kt
- skiko/src/macosMain/kotlin/org/jetbrains/skiko/Actuals.macos.kt
UIKit require permission to get clipboard content.
But, we can access method `generalPasteboard.hasStrings()` to get clipboard content. without permission.
It will help in this PR: https://github.com/JetBrains/androidx/pull/393
> UIKit Clipboard, simplify permission

- samples/SkiaAwtSample/src/main/kotlin/SkiaAwtSample/App.kt
- samples/SkiaAwtSample/src/main/kotlin/SkiaAwtSample/ClocksAwt.kt
- skiko/src/awtMain/cpp/windows/SoftwareRedrawer.cc
- skiko/src/awtMain/kotlin/org/jetbrains/skiko/context/SoftwareContextHandler.kt
- skiko/src/awtMain/kotlin/org/jetbrains/skiko/redrawer/Direct3DRedrawer.kt
- skiko/src/awtMain/kotlin/org/jetbrains/skiko/redrawer/WindowsSoftwareRedrawer.kt
- skiko/src/commonMain/kotlin/org/jetbrains/skia/PixelGeometry.kt
... and make software renderers respect the pixel geometry
We accidentally didn't prepare the `SurfaceProps` into an `IntArray` when passing them down into the JNI in the Windows version. The memory layout must have accidentally matched between both representations on Windows 10, but it doesn't work on Windows 11 for some reason. This is the proper fix.
> Fix passing of PixelGeometry to JNI on Windows 11

- skiko/src/commonMain/kotlin/org/jetbrains/skia/RuntimeShaderBuilder.kt
- skiko/src/commonTest/kotlin/org/jetbrains/skia/RuntimeShaderBuilderTest.kt
- skiko/src/jvmMain/cpp/common/RuntimeShaderBuilder.cc
- skiko/src/nativeJsMain/cpp/RuntimeShaderBuilder.cc
Porting of [`RuntimeShaderBuilder.makeShader`](https://github.com/google/skia/blob/17ec2b96242ddb4ac63c92e1701d2d5fc11855e2/include/effects/SkRuntimeEffect.h#L488) binding. 
Trying to follow the rest of the codebase. 
I need this binding in my project to concatenate RuntimeEffects in a single Shader.
> feat: add makeShader binding to RuntimeShaderBuilder

- skiko/src/commonMain/kotlin/org/jetbrains/skia/svg/SVGCanvas.kt
- skiko/src/jvmTest/kotlin/org/jetbrains/skia/svg/SVGCanvasTest.kt
Hi there 
I tried to use the SVGCanvas in some of our projects, but noticed that there was an `UnsatisfiedLinkError` when trying to use it.
```
'long org.jetbrains.skia.svg.SVGCanvasKt.SVGCanvas_nMake(float, float, float, float, long, int)'
java.lang.UnsatisfiedLinkError: 'long org.jetbrains.skia.svg.SVGCanvasKt.SVGCanvas_nMake(float, float, float, float, long, int)'
at org.jetbrains.skia.svg.SVGCanvasKt.SVGCanvas_nMake(Native Method)
at org.jetbrains.skia.svg.SVGCanvasKt.access$SVGCanvas_nMake(SVGCanvas.kt:1)
at org.jetbrains.skia.svg.SVGCanvas.make(SVGCanvas.kt:45)
at org.jetbrains.skia.svg.SVGCanvas.make(SVGCanvas.kt:25)
```
Upon further inspection I figured out that the `ExternalSymbolName` name was wrong and did not match up to the compiled symbol in the C++ JNI wrapper code. 
In …
> Add test in jvm for SVGCanvas and fix SVGCanvas JNI issue

- skiko/src/awtMain/kotlin/org/jetbrains/skiko/redrawer/MetalRedrawer.kt
- skiko/src/awtTest/kotlin/org/jetbrains/skiko/SkiaLayerTest.kt
MetalRedrawer may be disposed during update which leads to use after free
> prevent usage of dangling pointer to `MetalDevice`

- skiko/src/commonTest/kotlin/org/jetbrains/skia/ParagraphTest.kt
- skiko/src/jvmMain/cpp/common/interop.cc
`utfToUtf8` function (that converted ["modified UTF-8"](https://docs.oracle.com/javase/1.5.0/docs/guide/jni/spec/types.html#wp16542) to standard UTF-8) accesses out-of-bounds memory in case of invalid unicode and produces invalid UTF-8 output that causes future layouting issues.
`utfToUtf8` was replaced to UTF-16 -> UTF-8 conversion from skia library (patched version).
Fixes https://github.com/JetBrains/compose-multiplatform/issues/2963
> Fix JVM invalid unicode strings interop

- skiko/src/awtMain/kotlin/org/jetbrains/skiko/PlatformOperations.kt
- skiko/src/awtMain/kotlin/org/jetbrains/skiko/SkiaLayer.awt.kt
- skiko/src/awtTest/kotlin/org/jetbrains/skiko/SkiaLayerTest.kt
Fixed `FullscreenAdapter.fullscreen` to not be affected by the order of the calls to its listener methods.
Before this fix, showing a window with `fullscreen = true` would cause its `componentResized` method to be called before `componentShown`, which would then cause `_isFullscreen` to be assigned `false` and therefore `FullscreenAdapter .fullscreen` would return `false`.
It fixes https://github.com/JetBrains/compose-multiplatform/issues/3003 and also makes most of the `WindowStateTest` tests in https://github.com/JetBrains/compose-multiplatform-core that we currently disable on MacOS (and maybe Linux) pass.
> Fix FullscreenAdapter to be independent of the order of its listener calls

- samples/SkiaAwtSample/src/main/kotlin/SkiaAwtSample/SkiaPanel.kt
component listeners are performed to late so for absolute positioning we need to stick with `doLayout`
> fix `SwingSkia` example

- skiko/src/iosMain/kotlin/org/jetbrains/skiko/redrawer/MetalRedrawer.ios.kt
- skiko/src/macosMain/kotlin/org/jetbrains/skiko/redrawer/MetalRedrawer.macos.kt
Sometimes people crash on iOS simulator which glitched. Throwing an explicit exception stating the problem instead of force-unwrapping and wondering where NullPointerException in crash stacktrace came from should help us to discard unjustified issue reports.
> Throw exception instead of force unwrapping Metal handles when initialising MetalRedrawer.

- skiko/src/iosMain/kotlin/org/jetbrains/skiko/redrawer/MetalRedrawer.ios.kt
CADisplayLink should get preferredFramesPerSecond from max fps of UIScreen he is currently on, we didn't assign it previously and it's 60 fps by default.
> ProMotion screen support

- skiko/src/awtMain/kotlin/org/jetbrains/skiko/redrawer/MetalRedrawer.kt
- skiko/src/awtMain/objectiveC/macos/AWTMetalLayer.h
- skiko/src/awtMain/objectiveC/macos/AWTMetalLayer.mm
- skiko/src/awtMain/objectiveC/macos/MetalContextHandler.mm
- skiko/src/awtMain/objectiveC/macos/MetalDevice.h
- skiko/src/awtMain/objectiveC/macos/MetalDevice.mm
- skiko/src/awtMain/objectiveC/macos/MetalRedrawer.mm
- skiko/src/awtTest/kotlin/org/jetbrains/skiko/SkiaLayerTest.kt
- skiko/src/awtTest/kotlin/org/jetbrains/skiko/util/UiTest.kt
- skiko/src/commonMain/kotlin/org/jetbrains/skiko/FrameDispatcher.kt
- skiko/src/jvmMain/cpp/common/impl/Library.cc
The idea is to throttle command buffers creation on condition variable, awaking waiters on it only once vsync is coming.
- Implement blocking for generating commandBuffers with presentation using vsync. Vsync signals are controlled by DisplayLink which is dynamically created whenever NSWindow backing JPanel enters different screens (FPS can vary).
- Fix for potential problem with command buffers exhaustion, which can be arise in situation where CPU can encode commands faster, than GPU can render them (GPU bottleneck). In proposed implementation max 3 buffers can be inflight (as per triple buffering strategy).
- Minor refactor of Obj-C code and removal of redundant `@property` modifiers and nested `extern "C"`.
- NSWindow handle moved to MetalDevice
> Fix for losing presented drawables on JVM Mac OS

- skiko/src/commonMain/kotlin/org/jetbrains/skia/Canvas.kt
- skiko/src/commonTest/kotlin/org/jetbrains/skia/CanvasTest.kt
- skiko/src/jvmMain/cpp/common/Canvas.cc
- skiko/src/nativeJsMain/cpp/Canvas.cc
via the corresponding Skia functions directly, rather than by concatenating with a transformation matrix.
This appears to be significantly faster. Specifically in Compose, the canvas is translated for every node twice (by its position, and then back). Changing the `translate` function to perform a direct call to Skia transform makes drawing simple nodes much faster.
> Reimplement the Canvas transformation functions 

- skiko/src/awtMain/kotlin/org/jetbrains/skiko/ResourceUtils.kt
- skiko/src/awtMain/kotlin/org/jetbrains/skiko/swing/MetalSwingRedrawer.kt
- skiko/src/awtMain/kotlin/org/jetbrains/skiko/swing/SoftwareSwingRedrawer.kt
- skiko/src/awtMain/kotlin/org/jetbrains/skiko/swing/SwingRedrawerBase.kt
Remove DrawingSurfaceData, as it isn't used for all implementations, and adds null checks for the base class.
Also, remove initCanvas/flush, and replace them with `onRender`.
Instead, we can move neccessaryt logic to the implementations. Only one thing is duplicated in this PR - `canvas.clear(Color.TRANSPARENT)` + `skikoView.onRender`, but we can live with this.
> Refactoring of  Introduce separate SkiaSwingLayer for swing interop

- skiko/src/awtMain/objectiveC/macos/MetalRedrawer.mm
- skiko/src/macosMain/kotlin/org/jetbrains/skiko/redrawer/MetalRedrawer.macos.kt
Addition to #728
The problem on macOS was that the device is not cleared properly (for blending purposes), so blending might look different, but after this fix it
1. can be solved on user side (manual extra clearing)
2. it does not affect gooey effect demo (with compose)
So, it's not directly related to that and doesn't block this fix.
> Fix complex blending on Metal

- skiko/src/awtMain/kotlin/org/jetbrains/skiko/Actuals.awt.kt
- skiko/src/awtMain/kotlin/org/jetbrains/skiko/PlatformOperations.kt
- skiko/src/commonMain/kotlin/org/jetbrains/skiko/OsArch.kt
- skiko/src/jsMain/kotlin/org/jetbrains/skiko/OsArch.js.kt
- skiko/src/jsTest/kotlin/org/jetbrains/skiko/HostOsTest.kt
- skiko/src/jvmMain/kotlin/org/jetbrains/skiko/SkikoProperties.kt
It's going to be used in compose to propertly configure KeyMapping and other os-specific features/configurations (potentially for scroll physics, etc).
> Implement hostOs detection for web target

- skiko/RELEASE.md
- skiko/src/iosMain/kotlin/org/jetbrains/skiko/SkikoUIView.kt
- skiko/src/iosMain/kotlin/org/jetbrains/skiko/ios/UIKitKeyboardOptions.kt
Add UIKitKeyboardOptions in SikoUIView constructor arguments to forward Compose TextField keyboard options.
Need to resolve issues:
- https://github.com/JetBrains/compose-multiplatform/issues/2735
- https://github.com/JetBrains/compose-multiplatform/issues/2988
- https://github.com/JetBrains/compose-multiplatform/issues/2794
- https://github.com/JetBrains/compose-multiplatform/issues/3116
> iOS TextField add keyboard options

- skiko/src/iosMain/kotlin/org/jetbrains/skiko/SkikoUIView.kt
- skiko/src/iosMain/kotlin/org/jetbrains/skiko/ios/SkikoUITextInputTraits.kt
Rename interface to SkikoUITextInputTraits
It is better represented the purpose.
Also added missing functions from https://developer.apple.com/documentation/uikit/uitextinputtraits?language=objc
> iOS TextField, interface SkikoUITextInputTraits

- skiko/src/awtMain/kotlin/org/jetbrains/skiko/redrawer/DisplayLinkThrottler.kt
- skiko/src/awtMain/kotlin/org/jetbrains/skiko/redrawer/MetalRedrawer.kt
- skiko/src/awtMain/objectiveC/macos/DisplayLinkThrottler.mm
- skiko/src/awtMain/objectiveC/macos/MetalContextHandler.mm
- skiko/src/awtMain/objectiveC/macos/MetalDevice.h
- skiko/src/awtMain/objectiveC/macos/MetalRedrawer.mm
- skiko/src/awtTest/kotlin/org/jetbrains/skiko/SkiaLayerTest.kt
- skiko/src/awtTest/kotlin/org/jetbrains/skiko/util/UiTest.kt
Refactored version of https://github.com/JetBrains/skiko/pull/710
> Introduce vsync-based and overcommitment throttling to metal redrawer on macOS

- skiko/src/awtMain/kotlin/org/jetbrains/skiko/swing/MetalSwingRedrawer.kt
- skiko/src/awtMain/objectiveC/macos/MetalSwingRedrawer.mm
- skiko/src/commonMain/kotlin/org/jetbrains/skia/Bitmap.kt
There are 3 optimizations:
1. Reuse Metal texture if size is not changed
2. Reuse Bitmap where we read pixels from GPU and reallocate pixels only if size is changed
3. Reuse bytearray where we read raw pixels from bitmap, since now it is created for every readPixels (not sure about this one, since Bitmap is changed)
> Optimizations for Metal offscreen rendering for Swing interop

- skiko/src/commonMain/kotlin/org/jetbrains/skiko/context/ContextHandler.kt
- skiko/src/iosMain/kotlin/org/jetbrains/skiko/redrawer/MetalRedrawer.ios.kt
Draw could flush coroutines resulting in remeasurement, immediate invalidation and needRedraw reentry. Change the flag before the draw call to avoid this situation.
> Prevent needRedraw reentry on iOS

- skiko/src/iosMain/kotlin/org/jetbrains/skiko/SkikoUIView.kt
- skiko/src/iosMain/kotlin/org/jetbrains/skiko/redrawer/MetalRedrawer.ios.kt
The situation for which previous 3-state vsync tracking was introduced actually happened and caused violation of implicit internal compose invariant prohibiting synchronous draw during invalidation. Reverted back to minimal version using a bool flag to avoid redundant draw calls on blank vsyncs.
Fixes edge case of:
https://github.com/JetBrains/compose-multiplatform/issues/3396#issuecomment-1647516120
> Remove synchronous draw reentry logic inside needRedraw completely

- skiko/src/awtMain/kotlin/org/jetbrains/skiko/redrawer/MetalRedrawer.kt
- skiko/src/awtMain/objectiveC/macos/MetalContextHandler.mm
Drawable of right size will be presented from within `redrawImmediately`
https://github.com/JetBrains/skiko/assets/4167681/c56f7c40-5629-4b2f-8abf-1538192816fa
Fixes: https://github.com/JetBrains/compose-multiplatform/issues/3420
> Skip presenting CAMetalDrawable for CAMetalLayer that changed size

- skiko/src/iosMain/kotlin/org/jetbrains/skiko/SkikoUIView.kt
This comment was added with cinterop and def file in iOS. In def file was protocol UIViewExtensionProtocol. Now, we already removed UIViewExtensionProtocol.
> Remove old TODO comment

- skiko/src/awtMain/kotlin/org/jetbrains/skiko/MetalApi.kt
- skiko/src/awtMain/objectiveC/macos/MetalApi.mm
Correctly handle nulls when working with Obj-C API.
Throw RenderException if MTLDevice is null to allow RedrawerManager fallback to software renderer.
Minor refactor and typos fixes.
https://github.com/JetBrains/compose-multiplatform/issues/3460
https://github.com/JetBrains/skiko/issues/784
> Fix crash during MetalAdapter initialisation

- samples/SkiaAwtSample/src/main/kotlin/SkiaAwtSample/ClocksAwt.kt
- skiko/src/awtMain/cpp/windows/directXSwingRedrawer.cc
- skiko/src/awtMain/kotlin/org/jetbrains/skiko/swing/Direct3DSwingRedrawer.kt
Colors order should be BGRA since swing should receive ARGB in little endian. Previously it was RGBA, so colors were swapped
To reproduce run skiko sample with run interop.
> Change ordering of colors from RGBA to BGRA on DirectX offscreen rendering

- skiko/src/commonMain/kotlin/org/jetbrains/skia/svg/SVGLength.kt
- skiko/src/commonTest/kotlin/org/jetbrains/skia/SvgTest.kt
create a new SVGLength with a `_unit` from the input and not `this.unit`
___
It seems that this typo didn't cause any real issue so far. 
The only it was used in compose is here: https://github.com/JetBrains/compose-multiplatform-core/blob/bcaacc85477f959cac171b60258679b6244f512b/compose/ui/ui/src/desktopMain/kotlin/androidx/compose/ui/res/DesktopSvgResources.desktop.kt#L66
```kotlin
val width = root?.width?.withUnit(SVGLengthUnit.PX)?.value ?: 0f
val height = root?.height?.withUnit(SVGLengthUnit.PX)?.value ?: 0f
```
But here `withUnit` does nothing really useful, since `withUnit` doesn't do any conversion of the `value` - it preserves the original `value` .
> Fix SVGLength.withUnit

- .github/workflows/ci.yml
Add a step to automatically choose a device (iosSimulatorUUID) from `xcrun simctl list devices`
> Make CI automatically choose iPhone for tests

- skiko/build.gradle.kts
- skiko/src/awtMain/cpp/include/exceptions_handler.h
- skiko/src/awtMain/cpp/windows/OpenGLLibrary.cc
- skiko/src/awtMain/cpp/windows/SoftwareRedrawer.cc
- skiko/src/awtMain/cpp/windows/direct3DContext.cc
- skiko/src/awtMain/cpp/windows/directXRedrawer.cc
- skiko/src/awtMain/cpp/windows/exceptions_handler.cc
- skiko/src/awtMain/cpp/windows/openGLRedrawer.cc
- skiko/src/awtMain/kotlin/org/jetbrains/skiko/RenderExceptionsHandler.kt
- skiko/src/awtMain/kotlin/org/jetbrains/skiko/redrawer/LinuxOpenGLRedrawer.kt
- skiko/src/awtMain/kotlin/org/jetbrains/skiko/redrawer/WindowsOpenGLRedrawer.kt
- skiko/src/commonMain/kotlin/org/jetbrains/skiko/RenderException.kt
- skiko/src/jvmMain/cpp/common/openglapi.cc
- skiko/src/jvmMain/kotlin/org/jetbrains/skiko/OpenGLApi.kt
- skiko/src/jvmMain/kotlin/org/jetbrains/skiko/OpenGLLibrary.kt
Some Windows CI machines don't contain OpenGL, so Skiko/Compose will crash on them. It shouldn't crash, it should fallback to Software rendering
To properly fallback, we need to load opengl32.dll dynamically in runtime.
Fixes https://github.com/JetBrains/compose-multiplatform/issues/3243
- `gradlew publishToMavenLocal` is successful (if we use functions directly, it fails with "error LNK2019: unresolved external symbol")
- `SkiaLayerTest` is successful (it tests OpenGL as well)
1. Remove `C:\Windows\System32\opengl32.dll`
2. `SkiaLayerTest` still should be successful, but logs should contain that it fallbacks to Software rendering.
1. Compile local skiko
2. Run Compose run1 and tests
> Fix crash on Windows machines without OpenGL

- skiko/src/commonTest/kotlin/org/jetbrains/skia/ShaderTest.kt
- skiko/src/jvmMain/cpp/common/Shader.cc
Passing null into the "positions" parameter of a gradient shader factory that accepts a custom ColorSpace caused a segfault prior to this fix.
> Fix segfault of color space gradient makers upon pos=null

- skiko/src/awtMain/kotlin/org/jetbrains/skiko/redrawer/DispatcherToBlockOn.kt
After https://github.com/JetBrains/skiko/pull/798, we changed Dispatcher.IO to a custom dispatcher.
Dispatcher.IO is based on daemon threads (threads that receive InterruptedException on application exit).
Our new dispatcher isn't. The proof:
```
import java.util.concurrent.Executors
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.asCoroutineDispatcher
import kotlinx.coroutines.runBlocking
fun main() {
runBlocking(Dispatchers.IO) {
println(Thread.currentThread().isDaemon) // prints true
}
runBlocking(Executors.newCachedThreadPool().asCoroutineDispatcher()) {
println(Thread.currentThread().isDaemon) // prints false
}
val defaultFactory = Executors.defaultThreadFactory()
runBlocking(Executors.newCachedThreadPool {
defaultFactory.newThread(it).apply {
isDaemon = true
} …
```
> Make dispatcherToBlockOn dispatcher based on daemon threads.

- skiko/src/commonMain/kotlin/org/jetbrains/skia/PathUtils.kt
- skiko/src/commonTest/kotlin/org/jetbrains/skia/PathUtilsTest.kt
- skiko/src/jvmMain/cpp/common/PathUtils.cc
- skiko/src/nativeJsMain/cpp/PathUtils.cc
This functionality used to exist elsewhere in Skia & Skiko, but in Skia m110 it was moved into SkPathUtils. When that change occurred, the functionality was removed from Skiko rather than moved, so this commit is to return the functionality by providing access to SkPathUtils.
Resolves #797.
Notes:
- I've done my best to match the existing code for style consistency, let me know if I need to fix anything.
- The tests are simple as we are really just testing the bindings here, not necessarily their core functionality, which comes from Skia itself.
cc: @SergeevPavel here is my PR as we discussed, and thank you again for your help! 🙏
> Introduce SkPathUtils bindings

- skiko/ci/build.gradle.kts
Currently skiko-js is not uploaded to mavenCentral and we have an error when using only mavenCentral:
```
Could not resolve all dependencies for configuration ':jsApp:jsCompileClasspath'.
> Could not find org.jetbrains.skiko:skiko-js:0.7.85.
Searched in the following locations:
- https://dl.google.com/dl/android/maven2/org/jetbrains/skiko/skiko-js/0.7.85/skiko-js-0.7.85.pom
- https://repo.maven.apache.org/maven2/org/jetbrains/skiko/skiko-js/0.7.85/skiko-js-0.7.85.pom
Required by:
project :jsApp > org.jetbrains.compose.ui:ui:1.5.10-rc02 > org.jetbrains.compose.ui:ui-js:1.5.10-rc02 > org.jetbrains.skiko:skiko:0.7.85
> Could not resolve all dependencies for configuration ':shared:jsCompileClasspath'.
> Could not find org.jetbrains.skiko:skiko-js:0.7.85.
Required by:
project :shared > …
```
> Fix skiko-js mavenCentral publication: Add SkikoArtifacts.jsArtifactId to skikoArtifactIds list

- skiko/build.gradle.kts
With OS name and architecture moved to classifier, it would be easier to reference these artifacts in some Gradle features, such as dependency verification and locking.
> set OS name and architecture as archive classifier for JVM artifacts

- skiko/build.gradle.kts
- skiko/src/awtMain/kotlin/org/jetbrains/skiko/redrawer/MetalRedrawer.kt
- skiko/src/awtMain/objectiveC/macos/MetalDevice.h
- skiko/src/awtMain/objectiveC/macos/MetalRedrawer.mm
- skiko/src/awtTest/kotlin/org/jetbrains/skiko/SkiaLayerTest.kt
- skiko/src/awtTest/kotlin/org/jetbrains/skiko/util/UiTest.kt
- skiko/src/jvmMain/cpp/common/impl/Library.cc
Occasionally, when the window is just getting show, `isOccluded` will return `true` while we're already trying to draw into it. This causes `MetalRedrawer.draw` to delay for 300ms in order to avoid wasting resources drawing while the window is occluded. But because this delay is not interrupted even when the window becomes non-occluded, we get a delay drawing the 2nd frame.
This PR adds a call from native code `NSWindowDidChangeOcclusionStateNotification` that interrupts the delay when the window becomes non-occluded, so that drawing can resume immediately.
> In MetalRedrawer, stop delaying rendering as soon as the window becomes non-occluded.

- skiko/RELEASE.md
- skiko/src/nativeMain/kotlin/org/jetbrains/skia/impl/Native.native.kt
Previously it was a problem with converting  Kotlin `Array<String>` to C `char**`, because Kotlin String was conterted without Zero byte at the end.
> Fix problem with conversion of Kotlin String to C char *

- .github/workflows/ci.yml
- .github/workflows/web.yml
- skiko/karma.config.d/js/config.js
- skiko/src/commonTest/kotlin/org/jetbrains/skiko/tests/TestUtils.kt
- skiko/src/jsTest/kotlin/org/jetbrains/skiko/resourcePath.kt
- skiko/src/jsTest/kotlin/org/jetbrains/skiko/tests/TestUtils.js.kt
- skiko/src/jvmTest/kotlin/TestUtils.jvm.kt
- skiko/src/nativeTest/kotlin/org/jetbrains/skiko/tests/TestUtils.native.kt
- skiko/src/wasmJsTest/kotlin/org/jetbrains/skiko/tests/TestUtils.wasm.kt
Make resources reachable in tests
> Fix k/js tests

- samples/SkiaAwtSample/src/main/kotlin/SkiaAwtSample/App.kt
- skiko/src/awtMain/cpp/windows/directXRedrawer.cc
- skiko/src/awtMain/kotlin/org/jetbrains/skiko/redrawer/Direct3DRedrawer.kt
- skiko/src/commonMain/kotlin/org/jetbrains/skiko/SkiaLayer.kt
- skiko/src/jvmMain/cpp/common/stubs.cc
Required for https://github.com/JetBrains/compose-multiplatform-core/pull/915
Fixes #327
> Transparency support for D3D swap chain

- skiko/build.gradle.kts
- skiko/buildSrc/build.gradle.kts
- skiko/buildSrc/src/main/kotlin/SkikoProjectContext.kt
- skiko/buildSrc/src/main/kotlin/tasks/configuration/CommonTasksConfiguration.kt
- skiko/buildSrc/src/main/kotlin/tasks/configuration/JvmTasksConfiguration.kt
- skiko/buildSrc/src/main/kotlin/tasks/configuration/NativeTasksConfiguration.kt
- skiko/buildSrc/src/main/kotlin/tasks/configuration/WasmTasksConfiguration.kt
- skiko/gradle/wrapper/gradle-wrapper.properties
The goal of this PR is to make our build.gradle.kts file lighter to simplify working with it.
Around 1k lines were moved to new files in `buildSrc`, groupped by their purpose: wasm, native, jvm, common. 
___
The [SNAPSHOT](https://buildserver.labs.intellij.net/buildConfiguration/Skiko_PublishSnapshot/417771765) build was successfull.
> Split build.gradle.kts into smaller files

- skiko/src/commonMain/kotlin/org/jetbrains/skia/paragraph/LineMetrics.kt
- skiko/src/commonTest/kotlin/org/jetbrains/skia/ParagraphTest.kt
- skiko/src/commonTest/kotlin/org/jetbrains/skia/util/assertCloseEnough.kt
- skiko/src/nativeJsMain/cpp/paragraph/LineMetrics.cc
This contributes to fixing https://youtrack.jetbrains.com/issue/COMPOSE-108/CfW-fix-TextField-cursor
I had to introduce assertCloseEnough sensitive enought to path throughout all our targets
> Fix LineMetrics resolution for wasm and js targets

- samples/SkiaAwtSample/build.gradle.kts
- samples/SkiaMultiplatformSample/build.gradle.kts
- skiko/build.gradle.kts
* Argument -Xopt-in is deprecated. Please use -opt-in instead
* 'expect'/'actual' classes (including interfaces, objects, annotations, enums, and 'actual' typealiases) are in Beta
> [build] Following warning removed from skiko and samples

- samples/SkiaMultiplatformSample/src/iosMain/kotlin/org/jetbrains/skiko/sample/getSkikoViewContoller.kt
Add substituting logic for removed API.
Fixes: https://github.com/JetBrains/skiko/issues/852
> Fix iOS sample

- skiko/build.gradle.kts
- skiko/buildSrc/build.gradle.kts
- skiko/buildSrc/src/main/kotlin/properties.kt
- skiko/buildSrc/src/main/kotlin/tasks/configuration/JvmTasksConfiguration.kt
According to https://youtrack.jetbrains.com/articles/SRE-A-36/How-To-Use-CodeSign#by-codesign-client-utility
It was asked by SRE team.
> Download and use a codesign-client from an internal jb repository instead of using a hardcoded one

- skiko/src/awtMain/cpp/windows/directXRedrawer.cc
- skiko/src/awtMain/kotlin/org/jetbrains/skiko/context/Direct3DContextHandler.kt
- skiko/src/awtMain/kotlin/org/jetbrains/skiko/redrawer/Direct3DRedrawer.kt
Currently it fails to init swap chain because the size of the element is zero. It's not valid parameter in `DXGI_SWAP_CHAIN_DESC1`
`[SKIKO] warn: Exception in draw scope org.jetbrains.skiko.RenderException: Native exception in [Java_org_jetbrains_skiko_redrawer_Direct3DRedrawer_initSwapChain], code 3221225477: EXCEPTION_ACCESS_VIOLATION`
Fixes https://github.com/JetBrains/compose-multiplatform/issues/4105
> Don't try to init D3D with zero size

- skiko/build.gradle.kts
According to: https://youtrack.jetbrains.com/issue/COMPOSE-812/Review-dependency-on-unstable-coroutines-1.8.0-RC2
> Use coroutines 1.7.3 for desktop and native. But use 1.8.0-RC2 for web targets

- skiko/src/awtMain/kotlin/org/jetbrains/skiko/SystemTheme.awt.kt
- skiko/src/awtTest/kotlin/org/jetbrains/skiko/LibraryLoadedTest.kt
Fixes: https://github.com/JetBrains/compose-multiplatform/issues/4208
> Call `Library.load()` before calling native getCurrentSystemTheme()

- skiko/src/commonMain/kotlin/org/jetbrains/skia/IRect.kt
- skiko/src/commonMain/kotlin/org/jetbrains/skia/Rect.kt
Skia doesn't require such limitations during creation and [sorts](https://github.com/search?q=repo%3AJetBrains%2Fskia+.makeSorted%28%29+path%3A%2F%5Esrc%5C%2F%2F&type=code) values in a few methods during drawing.
Replacement of https://github.com/JetBrains/compose-multiplatform-core/pull/1062
Fixes https://github.com/JetBrains/compose-multiplatform/issues/4250
Fixes https://github.com/JetBrains/compose-multiplatform/issues/3794
Fixes https://github.com/JetBrains/compose-multiplatform/issues/3964
> Remove checks from Rect creation

- DEVELOPMENT.md
And move Windows instructions to the first section
Commands for Linux were get from https://github.com/JetBrains/skiko/blob/78f227f19bd4cb811d34fbc2df7befb4f76be355/.github/workflows/ci.yml#L102
Except we use `libx11-dev` instead of `xvfb`. Tested on a new system (but I performed commands in other order, so I am not completely sure that they are all needed)
> Update DEVELOPMENT.md instructions for Linux

- skiko/build.gradle.kts
> Use coroutines 1.8.0 for all targets

- skiko/src/awtMain/kotlin/org/jetbrains/skiko/swing/LinuxOpenGLSwingRedrawer.kt
Instead, fallback to Software.
Discovered during https://github.com/JetBrains/skiko/issues/876 investigation
We throw RenderException, and Fallback mechanism catches it and switches to Software
1. Setup the system without OpenGL
2. Run SkiaSwingLayer
3. See the native crash
> Offscreen, Linux. Fix native crash when OpenGL isn't available

- skiko/build-with-local-skia.sh
- skiko/buildSrc/src/main/kotlin/tasks/configuration/CommonTasksConfiguration.kt
- skiko/gradle.properties
- skiko/src/nativeMain/kotlin/org/jetbrains/skia/Actuals.native.kt
Now we build skia/icu with _skiko suffix to avoid clashes with Apple SDK
Corresponding skia change: https://github.com/JetBrains/skia/pull/3
Corresponding skia commit: https://github.com/JetBrains/skia/commit/47d3027b8cbeea76135c0995d5886aa2e58e7512
> Update skiko build for ICU renamed symbols

- skiko/src/awtMain/cpp/windows/directXRedrawer.cc
- skiko/src/awtMain/kotlin/org/jetbrains/skiko/redrawer/Direct3DRedrawer.kt
Merging a fix from `0.7.95.1` to the main branch for https://github.com/JetBrains/compose-multiplatform/issues/4397
> Use `CreateSwapChainForHwnd` without transparency

- skiko/src/awtMain/kotlin/org/jetbrains/skiko/context/Direct3DContextHandler.kt
- skiko/src/awtTest/kotlin/org/jetbrains/skiko/SkiaLayerTest.kt
Fixes https://github.com/JetBrains/compose-multiplatform/issues/4425
It is a regression after https://github.com/JetBrains/skiko/pull/858
The crash was because `d3dDevice->swapChain->GetBuffer` didn't return the buffer to draw on if we reused the buffer from the previous frame (we didn't change `surface` in case of zero size).
I am not completely sure why, but I exhausted my the investigation limit and this fix is needed by other reasons (we need to wait for vsync).
An additional check in the existed test (fails before the fix)
> Windows. Fix a crash when we resize to zero and then to non-zero

- samples/SkiaJsSample/src/jsMain/resources/index.html
- samples/SkiaJsSample/src/wasmJsMain/resources/index.html
- samples/SkiaMultiplatformSample/src/jsMain/kotlin/org/jetbrains/skiko/sample/App.js.kt
- samples/SkiaMultiplatformSample/src/wasmJsMain/kotlin/org/jetbrains/skiko/sample/App.wasm.kt
- skiko/src/jsMain/kotlin/org/jetbrains/skiko/SkiaLayer.js.kt
- skiko/src/jsWasmMain/kotlin/org/jetbrains/skiko/CanvasRenderer.kt
- skiko/src/jsWasmMain/kotlin/org/jetbrains/skiko/SkiaLayer.js.kt
- skiko/src/wasmJsMain/kotlin/org/jetbrains/skiko/SkiaLayer.js.wasmJs.kt
This is the skiko part of https://youtrack.jetbrains.com/issue/COMPOSE-1149/wasm-js-Remove-media-events-from-Skiko
This commit introduces following changes:
* CanvasRenderer is html-agnostic and deals with NativePointer
* SkiaLayer does not set any DOM dimensions of the canvas - it's up to the user of the Skia to resolve this dimensions
* Media event listeners are removed completely
> Remove media events from Skiko completely

- skiko/src/awtMain/kotlin/org/jetbrains/skiko/RenderExceptionsHandler.kt
- skiko/src/awtTest/kotlin/org/jetbrains/skiko/SeveralClassloadersTest.kt
- skiko/src/jvmMain/kotlin/org/jetbrains/skiko/Library.kt
- skiko/src/jvmMain/kotlin/org/jetbrains/skiko/SkikoProperties.kt
Skiko extracts binaries to `~/.skiko` by default, but it is not always possible. This PR adds a way to override the folder where to extract binaries:
```
System.setProperty("skiko.data.path", File(System.getProperty("java.io.tmpdir")).resolve(".skiko").toString())
```
Fixes https://github.com/JetBrains/skiko/issues/885
The case seems rare - we only have a crash in tests reported. If we have reports from real users, we  have to change the default `~/.skiko` to something else.
1. Run
```
import org.jetbrains.skia.Bitmap
import java.io.File
fun main() {
val path = File(System.getProperty("java.io.tmpdir")).resolve(".skiko").toString()
println(path)
System.setProperty("skiko.data.path", path)
Bitmap() // loads the library
}
```
2. See that `path` is created
The default way works:
```
import …
```
> System property to extract binaries to a different folder

- skiko/src/jvmMain/kotlin/org/jetbrains/skiko/OpenGLLibrary.jvm.kt
- skiko/src/jvmMain/kotlin/org/jetbrains/skiko/SkikoProperties.kt
To allow using OpenGL on macOs, call:
```
System.setProperty("skiko.macos.opengl.enabled", "true")
```
By request from user in DM who uses LWJGL+Skiko on macOS.
> Option to not throw RenderException when use OpenGL on macOS

- skiko/src/awtMain/kotlin/org/jetbrains/skiko/redrawer/RedrawerManager.kt
- skiko/src/awtMain/kotlin/org/jetbrains/skiko/swing/Direct3DSwingRedrawer.kt
Throw `RenderException` when constructing `Direct3DSwingRedrawer` with `nullptr` device. (Similar to `Direct3DRedrawer`)
To avoid crash in:
```
DirectXOffscreenDevice *d3dDevice = fromJavaPointer<DirectXOffscreenDevice *>(devicePtr);
GrD3DBackendContext backendContext = d3dDevice->backendContext;
return toJavaPointer(GrDirectContext::MakeDirect3D(backendContext).release());
```
Speculative fix for crash with a stack head below:
```
---------------  T H R E A D  ---------------
Current thread (0x000001cbcb0793f0):  JavaThread "AWT-EventQueue-0" [_thread_in_native, id=16744, stack(0x0000009488c00000,0x0000009488d00000)]
Stack: [0x0000009488c00000,0x0000009488d00000],  sp=0x0000009488cfc670,  free space=1009k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C …
```
> Fix crash when creating SwingRedrawer on DirectX

- skiko/src/awtMain/kotlin/org/jetbrains/skiko/Accessibility.kt
- skiko/src/awtMain/kotlin/org/jetbrains/skiko/HardwareLayer.kt
- skiko/src/awtMain/kotlin/org/jetbrains/skiko/swing/SkiaSwingLayer.kt
To properly support accessibility, SkiaSwingLayer needs to subclass `JPanel`, not `JComponent`.
Also, it needs to implement `requestNativeFocusOnAccessible`.
Fixes https://github.com/JetBrains/compose-multiplatform/issues/4731
Note that this doesn't yet fully fix a11y in `ComposePanel`. It still doesn't work well when Swing and Compose are mixed. `ComposePanel` appears to be highlighted as a whole, rather than individual widgets in it, by VoiceOver. It is, however, possible to go "inside" by focus traversal.
> Support accessibility in SkiaSwingLayer

- skiko/src/awtMain/objectiveC/macos/DisplayLinkThrottler.mm
Speculative fix for [a freeze issue](https://youtrack.jetbrains.com/issue/COMPOSE-1441/Desktop-skiko-freeze-after-sleep-on-Mac-with-multiple-external-monitors).
> Turn off vsync throttling when macOS hardware sleeps

- skiko/src/awtMain/kotlin/org/jetbrains/skiko/SkiaLayer.awt.kt
Fixes a couple of issues like: https://github.com/JetBrains/compose-multiplatform/issues/4744 (TODO: collect all references)
Before (slow-mo)
https://github.com/JetBrains/skiko/assets/1836384/5768b139-d08f-4142-8c14-2969107807f9
After (slow-mo)
https://github.com/JetBrains/skiko/assets/1836384/cc9a5103-3d30-412e-a5a4-baf590d657b8
> Redraw immediately on panel size change

- skiko/src/commonMain/kotlin/org/jetbrains/skia/paragraph/Paragraph.kt
It's unconditionally de-ref the pointer that causes crash in case of nulls
https://github.com/JetBrains/skiko/blob/c66eebc2c23a8b41eb618c715296c2a7dd135f43/skiko/src/jvmMain/cpp/common/paragraph/Paragraph.cc#L206
> Fix paint nullability for `updateForegroundPaint`/`updateBackgroundPaint`

- skiko/src/commonMain/kotlin/org/jetbrains/skia/Font.kt
- skiko/src/commonTest/kotlin/org/jetbrains/skia/FontTests.kt
- skiko/src/jvmMain/cpp/common/Font.cc
- skiko/src/nativeJsMain/cpp/Font.cc
Add forgotten setter for linear metrics. Changed it to property.
Original functions have names [`isLinearMetrics`](https://github.com/JetBrains/skia/blob/6726cd3e1ac4f30d6874c278008cdf24dfc9b470/include/core/SkFont.h#L115-L119C12) and [`setLinearMetrics`](https://github.com/JetBrains/skia/blob/6726cd3e1ac4f30d6874c278008cdf24dfc9b470/include/core/SkFont.h#L156-L163)
> Fix Font linear metrics binding

- .github/workflows/ci.yml
https://github.blog/changelog/2024-05-20-actions-upcoming-changes-to-github-hosted-macos-runners/
> Raise the macOs build agent from macos-11 to macos-12

- skiko/buildSrc/src/main/kotlin/SkikoProjectContext.kt
- skiko/buildSrc/src/main/kotlin/tasks/configuration/CommonTasksConfiguration.kt
- skiko/gradle.properties
One still can use optional platfrom-specific skia dependencies using exactly the property which was used before, however, by default all build targets are using the same version of skia prebuilt artefacts.
> All build targets have common skiaVersion which, however, can be overridden

- skiko/src/awtMain/kotlin/org/jetbrains/skiko/redrawer/DisplayLinkThrottler.kt
- skiko/src/awtMain/kotlin/org/jetbrains/skiko/redrawer/MetalRedrawer.kt
- skiko/src/awtMain/objectiveC/macos/DisplayLinkThrottler.mm
Usage of main-thread AppKit APIs in other thread is assumed to lead to the crash.
Second attempt for https://github.com/JetBrains/skiko/pull/958.
Structure display link control reactively around Wake/Sleep and Screen change notifications.
> Speculative fix for a crash

- .github/workflows/ci.yml
- skiko/buildSrc/src/main/kotlin/SkikoProjectContext.kt
The download directory path now depends on the buildType: Debug and Release
___
It affected our buildServer CI pipeline where it builds Release first and then Debug. And downloadTask was considered UP-TO-DATE when Debug build was attempted. Therefore the build used "Release" version of skia instead of "Debug. "
Added a Debug build to the githiub workflow too.
> Fix skia download destination directory

- skiko/src/commonTest/kotlin/org/jetbrains/skia/ManagedStringTest.kt
- skiko/src/jsMain/kotlin/org/jetbrains/skia/impl/Native.js.kt
- skiko/src/jsWasmMain/kotlin/org/jetbrains/skia/impl/Native.js.kt
- skiko/src/nativeJsMain/kotlin/org/jetbrains/skia/impl/Native.nativejs.kt
- skiko/src/nativeMain/kotlin/org/jetbrains/skia/impl/Native.native.kt
- skiko/src/wasmJsMain/kotlin/org/jetbrains/skia/impl/Native.wasm.kt
This is supposed to be fix for https://github.com/JetBrains/skiko/issues/967
The idea is pass strings as (utf8) byte arrays directly through the border
just like we do it on native
> Use convertToZeroTerminatedString on both wasm and js targets

- skiko/build.gradle.kts
- skiko/buildSrc/src/main/kotlin/properties.kt
- skiko/buildSrc/src/main/kotlin/tasks/configuration/CommonTasksConfiguration.kt
- skiko/buildSrc/src/main/kotlin/tasks/configuration/WasmTasksConfiguration.kt
Adding a new flag `-Pskiko.wasm.withProfiling=true` which adds `--profiling` flag to emcc, so it preserves the function names - makes it easier to use the browser profiler.
By default, it's disabled.
> Preserve profiling information in skiko.wasm with an extra build flag

- skiko/gradle.properties
- skiko/src/commonMain/kotlin/org/jetbrains/skia/paragraph/StrutStyle.kt
- skiko/src/commonMain/kotlin/org/jetbrains/skia/paragraph/TextStyle.kt
- skiko/src/commonTest/kotlin/org/jetbrains/skiko/paragraph/TextStyleTest.kt
- skiko/src/jvmMain/cpp/common/paragraph/StrutStyle.cc
- skiko/src/jvmMain/cpp/common/paragraph/TextStyle.cc
- skiko/src/nativeJsMain/cpp/paragraph/StrutStyle.cc
- skiko/src/nativeJsMain/cpp/paragraph/TextStyle.cc
Support configurable vertical centering for implementing Compose's `LineHeightStyle.Alignment`.
https://youtrack.jetbrains.com/issue/CMP-2602
See also:
- https://github.com/JetBrains/skia/pull/5
- https://github.com/JetBrains/compose-multiplatform-core/pull/1569
> Replace half leading to top ratio

- skiko/src/uikitMain/kotlin/org/jetbrains/skiko/Actuals.uikit.kt
Fixes the following error when calling `URIHandler_openUri` on iOS 18:
```
The caller of UIApplication.openURL(_:) needs to migrate to the non-deprecated UIApplication.open(_:options:completionHandler:). Force returning false (NO).
```
Fixes: https://youtrack.jetbrains.com/issue/CMP-6699
> Use actual openURL method on iOS

- skiko/src/awtMain/kotlin/org/jetbrains/skiko/swing/SwingOffscreenDrawer.kt
Fix for https://youtrack.jetbrains.com/issue/CMP-6722/Excessive-garbage-generation-from-redrawing
Previously, the `draw` method would allocate a `BufferedImage` on every redraw, which is wasteful. This fix changed `SwingOffscreenRenderer` to reuse the same instance of `BufferedImage` and only clear it on redraws. Only changing the draw size would allocate a new `BufferedImage`.
> Reuse the BufferedImage in SwingOffscreenRenderer

- .github/workflows/ci.yml
Reason: macos-12 is deprecated and not available anymore https://github.com/actions/runner-images/issues/10721 
(Several previous CI runs were incomplete bacause of this: https://github.com/JetBrains/skiko/actions, including a commit merged to master - https://github.com/JetBrains/skiko/commit/bccb17a47610b17ee5e297d3665b4fc0625da9e1)
> Update macos runner to 13

- skiko/buildSrc/src/main/kotlin/tasks/configuration/NativeTasksConfiguration.kt
This is an alternative (better) fix for https://youtrack.jetbrains.com/issue/CMP-6721 
Similar change is skia is required too: https://github.com/JetBrains/skia-pack/pull/60
> Set -mios-simulator-version-min=12.0 for skiko build

- skiko/src/awtMain/objectiveC/macos/DisplayLinkThrottler.mm
- skiko/src/awtMain/objectiveC/macos/MetalRedrawer.mm
Fixes
https://youtrack.jetbrains.com/issue/CMP-7352
https://youtrack.jetbrains.com/issue/CMP-7345
> Fix macOS transparent windows on OpenJDK

- skiko/src/commonMain/kotlin/org/jetbrains/skia/PaintFilterCanvas.kt
- skiko/src/commonMain/kotlin/org/jetbrains/skia/Picture.kt
- skiko/src/commonMain/kotlin/org/jetbrains/skia/PictureFilterCanvas.kt
- skiko/src/jvmMain/cpp/common/PaintFilterCanvas.cc
- skiko/src/jvmMain/cpp/common/PictureFilterCanvas.cc
- skiko/src/jvmMain/cpp/common/interop.cc
- skiko/src/jvmMain/cpp/common/interop.hh
- skiko/src/jvmMain/kotlin/org/jetbrains/skia/PictureFilterCanvas.jvm.kt
- skiko/src/nativeJsMain/cpp/PaintFilterCanvas.cc
- skiko/src/nativeJsMain/cpp/PictureFilterCanvas.cc
- skiko/src/nativeJsMain/kotlin/org/jetbrains/skia/PaintFilterCanvas.nativejs.kt
- skiko/src/nativeJsMain/kotlin/org/jetbrains/skia/PictureFilterCanvas.nativeJs.kt
New `PictureFilterCanvas` class that allows override picture rendering during drawing
Required for https://github.com/JetBrains/compose-multiplatform-core/pull/1766
> Add a way to replace picture placeholders during drawing

- skiko/src/awtMain/kotlin/org/jetbrains/skiko/SkiaLayer.awt.kt
- skiko/src/awtTest/kotlin/org/jetbrains/skiko/SkiaLayerTest.kt
Calling `SkiaLayer.revalidate()` when the window moves causes unnecessary layout and repainting.
This PR makes sure to only call it when the actual position of the layer in the window changes.
> Avoid calling SkiaLayer.revalidate() when the window itself is moved.

- .github/workflows/ci.yml
- skiko/build.gradle.kts
Currently fails with
```
Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v3`. Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
```
> Update actions/upload-artifact to v4

- skiko/src/commonMain/kotlin/org/jetbrains/skia/BreakIterator.kt
- skiko/src/commonTest/kotlin/org/jetbrains/skia/BreakIteratorTests.kt
- skiko/src/jvmMain/cpp/common/BreakIterator.cc
- skiko/src/nativeJsMain/cpp/BreakIterator.cc
This PR is split-off from and is a prerequisite of Clang-cl PR: #1020
BreakIterator.clone() is broken on JVM and seemingly leads to a use-after-free behaviour. Clang-cl makes this issue more visible, likely due to address sanitisation.
Explanation why it is deleted in an internal channel: https://jetbrains.slack.com/archives/C02DDNREC77/p1738678000232729
* `breakIteratorCloneTest` is failing with an access violation in Debug mode with additional checks, so using it wasn't safe
* it is not used anywhere
This is a breaking change and will require bumping Skiko version to 0.9.0.
> Remove BreakIterator.clone() method

- DEVELOPMENT.md
- skiko/buildSrc/src/main/kotlin/CompileSkikoCppTask.kt
- skiko/buildSrc/src/main/kotlin/properties.kt
- skiko/buildSrc/src/main/kotlin/tasks/configuration/JvmTasksConfiguration.kt
- skiko/gradle.properties
- skiko/src/awtMain/cpp/windows/InternalDirectXApi.cc
- skiko/src/awtMain/cpp/windows/SoftwareRedrawer.cc
- skiko/src/awtMain/cpp/windows/directXRedrawer.cc
- skiko/src/awtMain/cpp/windows/exceptions_handler.cc
Official Skia documentation suggests that it's [_highly recommended_](https://skia.org/docs/user/build/#highly-recommended-build-with-clang-cl) to build Skia with Clang-CL on Windows, and that this dramatically improves Skia performance with Software rendering and in other areas. This corresponds with my experience, so here it is.
Related Skia-pack PR: https://github.com/JetBrains/skia-pack/pull/64
Prerequisite: #1024
> Build Skiko with Clang-CL

- skiko/src/awtMain/kotlin/org/jetbrains/skiko/redrawer/MetalRedrawer.kt
- skiko/src/macosMain/kotlin/org/jetbrains/skiko/redrawer/MetalRedrawer.macos.kt
My app is used a lot in the background, and I noticed high CPU usage in the native macOS version. With this PR, CPU usage is reduced when window is invisible by disabling drawing. This was already implemented for the JVM, and that behaviour is now copied to native macOS. So the code is similar to JVM parts in:
- https://github.com/JetBrains/skiko/blob/master/skiko/src/awtMain/kotlin/org/jetbrains/skiko/redrawer/MetalRedrawer.kt
- https://github.com/JetBrains/skiko/blob/master/skiko/src/awtMain/objectiveC/macos/MetalRedrawer.mm
The draw function is now suspend, which required moving some other functions around. I tried to keep the implementation similar to the JVM version.
Tested using `./gradlew runNative` in `samples/SkiaMultiplatformSample`. Now the CPU usage is reduced a lot when …
> Fix high CPU usage when window is occluded on macOS Native

- skiko/src/commonMain/kotlin/org/jetbrains/skia/CodePoint.kt
- skiko/src/commonMain/kotlin/org/jetbrains/skia/Expects.kt
- skiko/src/commonMain/kotlin/org/jetbrains/skia/Font.kt
- skiko/src/commonMain/kotlin/org/jetbrains/skia/Typeface.kt
- skiko/src/commonMain/kotlin/org/jetbrains/skia/icu/Unicode.kt
- skiko/src/commonTest/kotlin/org/jetbrains/skia/icu/UnicodeTest.kt
- skiko/src/jsWasmMain/kotlin/org/jetbrains/skia/Actuals.js.kt
- skiko/src/jvmMain/cpp/common/icu/Unicode.cc
- skiko/src/jvmMain/kotlin/org/jetbrains/skia/Actuals.jvm.kt
- skiko/src/nativeJsMain/cpp/icu/Unicode.cc
- skiko/src/nativeMain/kotlin/org/jetbrains/skia/Actuals.native.kt
This is needed to detect emojis in Compose Multiplatform.
Also, it looks like the native implementations of `String.intCodePoints()` were broken. I fixed them by copying the relevant code from Compose.
> Expose ICUs u_hasBinaryProperty

- skiko/src/awtMain/objectiveC/macos/MetalRedrawer.mm
Flushing the transaction causes the window background to be visible for a frame when closing the window. 
Fixes: https://youtrack.jetbrains.com/issue/CMP-5651
This reverts https://github.com/JetBrains/skiko/pull/552. I have tested the IDE sample from Jewel, and that issue does not seem to reproduce anymore, even without flushing the transaction.
https://github.com/user-attachments/assets/a3c7c0ab-2342-4cae-8c52-669faeb1f516
> Fix the background flashing when closing a window/dialog.

- skiko/src/awtMain/kotlin/org/jetbrains/skiko/Actuals.awt.kt
- skiko/src/awtMain/kotlin/org/jetbrains/skiko/SkiaLayer.awt.kt
- skiko/src/awtMain/kotlin/org/jetbrains/skiko/redrawer/RedrawerManager.kt
- skiko/src/awtMain/kotlin/org/jetbrains/skiko/swing/SkiaSwingLayer.kt
- skiko/src/awtTest/kotlin/org/jetbrains/skiko/SkiaLayerTest.kt
- skiko/src/jvmMain/kotlin/org/jetbrains/skiko/RenderFactory.kt
Currently, these listeners are only called when the `renderApi` is set manually, not when it changes to a fallback.
> Call the listeners of PropertyKind.Renderer on render API fallback

- skiko/src/awtMain/objectiveC/macos/MetalRedrawer.mm
Creating transparent views/renderers shouldn't disable window shadows
Context: [CMP-7752](https://youtrack.jetbrains.com/issue/CMP-7752) Interop blending should not disable window shadows on macOS
> Do not change window properties during `MetalRedrawer` creation

- samples/SkiaMultiplatformSample/src/commonMain/kotlin/org/jetbrains/skiko/sample/EmojiStory.kt
- skiko/src/commonMain/kotlin/org/jetbrains/skia/paragraph/ParagraphStyle.kt
- skiko/src/commonTest/kotlin/org/jetbrains/skia/ParagraphTest.kt
- skiko/src/jsWasmTest/kotlin/org/jetbrains/skia/ParagraphWebTest.kt
- skiko/src/jvmMain/cpp/common/paragraph/ParagraphStyle.cc
- skiko/src/nativeJsMain/cpp/paragraph/ParagraphStyle.cc
This change will be used in Compose Multiplatform to fix https://youtrack.jetbrains.com/issue/CMP-6589/wasm-can-not-render-tab-symbol 
The difference can be seen here:
**Good**: https://fiddle.skia.org/c/24fb7ebc20eec08077d84b9fe37ceb4f  - `paraStyle.setReplaceTabCharacters(true);`
**Bad**: https://fiddle.skia.org/c/fbcb4a52786d63ed42a85d05d5472164 - `paraStyle.setReplaceTabCharacters(false);`
> Add a getter and setter for ParagraphStyle.replaceTabCharacters

- skiko/src/awtMain/kotlin/org/jetbrains/skiko/redrawer/MetalRedrawer.kt
- skiko/src/awtTest/kotlin/org/jetbrains/skiko/SkiaLayerTest.kt
- skiko/src/awtTest/kotlin/org/jetbrains/skiko/util/UiTest.kt
- skiko/src/commonMain/kotlin/org/jetbrains/skiko/Logging.kt
1. In `DefaultConsoleLogger.fromLevel` use `LogLevel.entries.firstOrNull` instead of `LogLevel.values().filter().firstOrNull`.
2. `UiTestWindow` does not need to override `dispose` to dispose the layer, as the layer disposes itself when the window is disposed (from `removeNotify`).
3. Remove `MetalRedrawer.drawSync`, which was only used in tests, as there's already `redrawImmediately`.
> Minor cleanup.

- skiko/src/awtMain/kotlin/org/jetbrains/skiko/SkiaLayer.awt.kt
- skiko/src/awtMain/objectiveC/macos/MetalRedrawer.mm
- skiko/src/awtTest/kotlin/org/jetbrains/skiko/SkiaLayerTest.kt
The issue with flashing on dispose is fixed by disabling `displaySyncEnabled` on the native layer in `MetalRedrawer_disposeDevice`.
The issue with flashing on hide is fixed by avoiding a call to `MetalRedrawer.setVisible(false)` in the particular scenario of the window becoming hidden.
> [Metal] Fix window background flash on dispose/hide while animation is running

- samples/SkiaMultiplatformSample/src/awtMain/kotlin/org/jetbrains/skiko/sample/AwtClocks.kt
- samples/SkiaMultiplatformSample/src/commonMain/kotlin/org/jetbrains/skiko/sample/Clocks.kt
- samples/SkiaMultiplatformSample/src/macosMain/kotlin/org/jetbrains/skiko/sample/MacosClocks.kt
- samples/SkiaMultiplatformSample/src/uikitMain/kotlin/org/jetbrains/skiko/sample/IosClocks.kt
- samples/SkiaMultiplatformSample/src/webMain/kotlin/org/jetbrains/skiko/sample/WebClocks.web.kt
renderApi can change if there was a fallback (DIRECT3D -> OpenGL -> Software). We need to always call it in the frame.
Noticed it during testing.
> SkiaMultiplatformSample. Fix showing render API after fallback

- README.md
https://jetbrains.slack.com/archives/C02DDNREC77/p1744211587478839?thread_ts=1744180296.015109&cid=C02DDNREC77
- now 0.0.1-SNAPSHOT is built
- it can't be used, as it is built from any branch, not only from master
> Remove 0.0.0-SNAPSHOT note

- skiko/src/awtMain/cpp/windows/OpenGLLibrary.cc
- skiko/src/awtMain/kotlin/org/jetbrains/skiko/redrawer/LinuxOpenGLRedrawer.kt
- skiko/src/jvmMain/cpp/common/openglapi.cc
- skiko/src/jvmMain/kotlin/org/jetbrains/skiko/OpenGLApi.kt
We have a situation on a Linux where a significant portion of time spent in EDT is spent inside a `glFinish()` call.
OS: Linux bazhenov 6.11.0-19-generic #19~24.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Feb 17 11:51:52 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
Distribution: Ubuntu 24.04
GPU: Intel Corporation AlderLake-S GT1 [8086:4680] (rev 0c) (Intel UHD Graphics 770)
Driver: i915
According to the [documentation](https://registry.khronos.org/OpenGL-Refpages/gl4/html/glFinish.xhtml):
> glFinish does not return until the effects of all previously called GL commands are complete. Such effects include all changes to GL state, all changes to connection state, and all changes to the frame buffer contents.
It effectively means that there is no overlap in work being done on the CPU and GPU; we only start …
> Using glFlush() instead of glFinish()

- samples/SkiaAndroidSample/build.gradle.kts
- skiko/buildSrc/src/main/kotlin/tasks/configuration/CommonTasksConfiguration.kt
"AndroidRelease" should be used instead of "Android" since using the android plugin introduces release/debug variants.
Note: `./gradlew publish -Pskiko.android.enabled=true` would still fail with the following, but this task is as I understand not used on CI and "build repo" seem to be a local thing.
```
> Task :publishAndroidReleasePublicationToBuildRepoRepository FAILED
FAILURE: Build failed with an exception.
* What went wrong:
A problem was found with the configuration of task ':publishAndroidReleasePublicationToBuildRepoRepository' (type 'PublishToMavenRepository').
- Gradle detected a problem with the following location: '/Users/cdelabou/workspace/misc/skiko/skiko/build/libs/skiko-0.0.0-SNAPSHOT-javadoc.jar.asc'.
Reason: Task ':publishAndroidReleasePublicationToBuildRepoRepository' …
```
> Make configureSignAndPublishDependencies use proper android task names

- .github/workflows/ci.yml
- .github/workflows/web.yml
The current runners fail with:
This is a scheduled Ubuntu 20.04 retirement. Ubuntu 20.04 LTS runner will be removed on 2025-04-15. For more details, see https://github.com/actions/runner-images/issues/11101
GitHub Actions has encountered an internal error when running your job.
> Update runners to ubuntu-22.04

- samples/SkiaAwtSample/build.gradle.kts
- skiko/build.gradle.kts
- skiko/src/awtMain/kotlin/org/jetbrains/skiko/swing/AcceleratedSwingPainter.kt
- skiko/src/awtMain/kotlin/org/jetbrains/skiko/swing/Direct3DSwingRedrawer.kt
- skiko/src/awtMain/kotlin/org/jetbrains/skiko/swing/LinuxOpenGLSwingRedrawer.kt
- skiko/src/awtMain/kotlin/org/jetbrains/skiko/swing/MetalSwingRedrawer.kt
- skiko/src/awtMain/kotlin/org/jetbrains/skiko/swing/SoftwareSwingPainter.kt
- skiko/src/awtMain/kotlin/org/jetbrains/skiko/swing/SoftwareSwingRedrawer.kt
- skiko/src/awtMain/kotlin/org/jetbrains/skiko/swing/SwingOffscreenDrawer.kt
- skiko/src/awtMain/kotlin/org/jetbrains/skiko/swing/SwingPainter.kt
This PR contain:
1. Using shared metal textures with this JBR API - [SharedTextures](https://github.com/JetBrains/JetBrainsRuntimeApi/blob/main/src/com/jetbrains/SharedTextures.java). See `AcceleratedSwingPainter`.
2. Not ultimate, but visible improvement of the not accelerated painting for Windows(~%25), and MacOS(~20%). Unfortunately, didn't manage to see a positive change on Linux with XRender pipeline(about the same, probably few percents down). With opengl pipeline it also got ~20% faster. But currently our pipeline on linux is XRender
I got rid of make one extra copy of the raster image. See `SoftwareSwingPainter`
`com.jetbrains:jbr-api` size is about 44kb
Benchmarks:
`Redraw` - time to prepare the offscreen image including sync, but not including fetching texture to the CPU RAM …
> metal: accelerate swing rendering

- skiko/buildSrc/build.gradle.kts
- skiko/buildSrc/gradle.properties
- skiko/gradle.properties
- skiko/settings.gradle.kts
This PR solves misleading kotlin.version parametrization which actually was not working as expected: The actual version was always resolved from buildSrc.
some context
https://jetbrains.slack.com/archives/C0288G57R/p1749820141169649
> [build] Correct kotlin.version parametrizaton in skiko/skiko

- .github/workflows/ci.yml
- skiko/buildSrc/src/main/kotlin/tasks/configuration/JvmTasksConfiguration.kt
- skiko/src/awtMain/cpp/linux/swingRedrawer.cc
- skiko/src/awtTest/kotlin/org/jetbrains/skiko/SkiaLayerTest.kt
- skiko/src/awtTest/kotlin/org/jetbrains/skiko/util/UiTest.kt
Fixes https://youtrack.jetbrains.com/issue/CMP-8936
`glXChooseFBConfig` fails to find a config with `GLX_DOUBLEBUFFER, False` on my machine, it only has double buffered configs. But double/single buffering doesn't matter as we use pixel buffers.
Also choose a correct config that is required by https://registry.khronos.org/OpenGL-Refpages/gl2.1/xhtml/glXCreatePbuffer.xml:
```
BadMatch is generated if config does not support rendering to pixel buffers (e.g., GLX_DRAWABLE_TYPE does not contain GLX_PBUFFER_BIT)
```
- manually, in the clocks example
- the modified test failed before the fix, now it doesn't fail
Fix "SkiaSwingLayer doesn't use hardware acceleration on Linux"
Fix "ComposePanel doesn't use hardware acceleration with RenderSettings.SwingGraphics on Linux"
> Fix "ComposePanel doesn't use hardware acceleration with RenderSettings.SwingGraphics on Linux"
