JetBrains/skiko

README.md
=> #36. Fix maven repository link in README

skiko/src/jvmMain/kotlin/org/jetbrains/skiko/SkiaLayer.kt
We probably shouldn't perform frame rendering in init/setBounds.
Because in onRender we can call window.setBounds.
It will cause drawing onRender inside another onRender.
After the fix there is no increase in artifacts on start or resize.
"True" fix would be to call "repaint" instead of manual scheduling redrawing with "invokeLater", because paint events have higher priority than usual events.
But "repaint" doesn't work with Canvas. It is only works with Swing components.
We can extend JLayeredPane instead of HardwareLayer (and just add HardwareLayer to JLayeredPane).
But there are too much changes.
Anyway, system draws Window independently of AWT, so we probably can't get rid of artifacts if we use only AWT.
=> Schedule redraw on resize and initialization

skiko/src/jvmMain/cpp/common/render.cc, skiko/src/jvmMain/kotlin/org/jetbrains/skiko/RenderTargets.kt, skiko/src/jvmMain/kotlin/org/jetbrains/skiko/SkiaLayer.kt, skiko/src/jvmMain/kotlin/org/jetbrains/skiko/context/ContextHandler.kt, skiko/src/jvmMain/kotlin/org/jetbrains/skiko/context/Direct3DContextHandler.kt, skiko/src/jvmMain/kotlin/org/jetbrains/skiko/context/MetalContextHandler.kt, skiko/src/jvmMain/kotlin/org/jetbrains/skiko/context/OpenGLContextHandler.kt, skiko/src/jvmMain/kotlin/org/jetbrains/skiko/context/SoftwareContextHandler.kt, skiko/src/jvmMain/kotlin/org/jetbrains/skiko/redrawer/Direct3DRedrawer.kt
There were NullPointerException.
Also rename dispose to disposeCanvas.
And add method "dispose" for full dispose
=> Fix "open windows stress test"

skiko/src/jvmMain/kotlin/org/jetbrains/skiko/SkiaLayer.kt
This is because we add listeners to Canvas, but at window start we take focus on parent JPanel.
We can't add listeners to JPanel, because Canvas will eat all events anyway.
=> Compose. Hot keys didn't work until we clicked on the window.

samples/SkijaInjectSample/src/main/kotlin/SkijaInjectSample/App.kt, skiko/src/jvmMain/cpp/windows/directXRedrawer.cc, skiko/src/jvmMain/kotlin/org/jetbrains/skiko/context/ContextHandler.kt, skiko/src/jvmMain/kotlin/org/jetbrains/skiko/context/Direct3DContextHandler.kt, skiko/src/jvmMain/kotlin/org/jetbrains/skiko/context/OpenGLContextHandler.kt, skiko/src/jvmMain/kotlin/org/jetbrains/skiko/redrawer/Direct3DRedrawer.kt
Must be properly tested before merging.
=> Resize reinit refactor

samples/SkijaInjectSample/src/main/kotlin/SkijaInjectSample/App.kt, skiko/src/jvmMain/kotlin/org/jetbrains/skiko/OsArch.kt, skiko/src/jvmMain/kotlin/org/jetbrains/skiko/context/ContextHandler.kt, skiko/src/jvmMain/kotlin/org/jetbrains/skiko/context/Direct3DContextHandler.kt, skiko/src/jvmMain/kotlin/org/jetbrains/skiko/context/MetalContextHandler.kt, skiko/src/jvmMain/kotlin/org/jetbrains/skiko/context/OpenGLContextHandler.kt, skiko/src/jvmMain/kotlin/org/jetbrains/skiko/context/SoftwareContextHandler.kt
Added in debug output info about current JDK and current OS name/version/architecture.
=> Added OS/JRE info in debug output.

samples/SkijaInjectSample/src/main/kotlin/SkijaInjectSample/App.kt, skiko/src/jvmMain/cpp/windows/directXRedrawer.cc, skiko/src/jvmMain/kotlin/org/jetbrains/skiko/GraphicsApi.kt, skiko/src/jvmMain/kotlin/org/jetbrains/skiko/redrawer/Direct3DRedrawer.kt, skiko/src/jvmMain/kotlin/org/jetbrains/skiko/redrawer/MetalRedrawer.kt, skiko/src/jvmMain/objectiveC/macos/MetalRedrawer.mm
More flexible adapter selection in Metal and DirectX rendering via properties (skiko.metal.gpu.priority, skiko.derectx.gpu.priority).
=> Adapter priority

skiko/gradle.properties
This is needed in our new secret IDE
=> Bump Skija 0.91.3 -> 0.91.6

skiko/build.gradle.kts, skiko/src/jvmMain/kotlin/org/jetbrains/skiko/Library.kt, skiko/src/jvmTest/kotlin/org/jetbrains/skiko/SeveralClassloaders.kt
This change fixes an exception,
when Skiko is loaded multiple times
in a multi-classloader environment on Windows:
java.lang.RuntimeException: Can't wrap nullptr
at org.jetbrains.skija.impl.Native.<init>(Native.java:13)
at org.jetbrains.skija.impl.Managed.<init>(Managed.java:15)
at org.jetbrains.skija.impl.Managed.<init>(Managed.java:11)
at org.jetbrains.skija.paragraph.ParagraphBuilder.<init>(ParagraphBuilder.java:15)
The exception was happening, because
when `skiko.library.path` is not set,
icudtl.dat was copied into cacheDir,
even if the library was copied into copyDir.
Also icudtl.dat was always copied to `java.io.tmpdir`,
and a different version was not overwritten.
=> Always copy icudtl.dat with skiko.dll

.github/workflows/blank.yml, samples/SkiaJvmSample/build.gradle.kts, skiko/build.gradle.kts, skiko/docker/linux-amd64/Dockerfile, skiko/docker/linux-arm64/Dockerfile, skiko/src/jvmMain/cpp/linux/awt.cc, skiko/src/jvmMain/cpp/linux/display.cc, skiko/src/jvmMain/cpp/linux/redrawer.cc, skiko/src/jvmMain/kotlin/org/jetbrains/skiko/AWTLinuxDrawingSurface.kt, skiko/src/jvmMain/kotlin/org/jetbrains/skiko/Display.kt, skiko/src/jvmMain/kotlin/org/jetbrains/skiko/FrameLimiter.kt, skiko/src/jvmMain/kotlin/org/jetbrains/skiko/PlatformOperations.kt, skiko/src/jvmMain/kotlin/org/jetbrains/skiko/RendezvousBroadcastChannel.kt, skiko/src/jvmMain/kotlin/org/jetbrains/skiko/SkiaLayerProperties.kt, skiko/src/jvmMain/kotlin/org/jetbrains/skiko/SkikoProperties.kt, skiko/src/jvmMain/kotlin/org/jetbrains/skiko/redrawer/LinuxOpenGLRedrawer.kt, skiko/src/jvmMain/kotlin/org/jetbrains/skiko/redrawer/SoftwareRedrawer.kt, skiko/src/jvmTest/kotlin/org/jetbrains/skiko/FrameLimiterTest.kt, skiko/src/jvmTest/kotlin/org/jetbrains/skiko/RendezvousBroadcastChannelTest.kt
Otherwise there is no delay between frames and we will have high CPU usage
=> Emulate vsync tick on Software renderer and Linux with unsupported vsync

skiko/src/jvmMain/kotlin/org/jetbrains/skiko/SkiaLayer.kt, skiko/src/jvmMain/kotlin/org/jetbrains/skiko/redrawer/AngleRedrawer.kt, skiko/src/jvmMain/kotlin/org/jetbrains/skiko/redrawer/Direct3DRedrawer.kt, skiko/src/jvmMain/kotlin/org/jetbrains/skiko/redrawer/LinuxOpenGLRedrawer.kt, skiko/src/jvmMain/kotlin/org/jetbrains/skiko/redrawer/MetalRedrawer.kt, skiko/src/jvmMain/kotlin/org/jetbrains/skiko/redrawer/SoftwareRedrawer.kt, skiko/src/jvmMain/kotlin/org/jetbrains/skiko/redrawer/WindowsOpenGLRedrawer.kt
Partially fix https://github.com/JetBrains/skiko/issues/137
=> Don't draw if window is invisible (JFrame.isVisible = false)

samples/SkiaJsSample/build.gradle.kts, samples/SkiaJsSample/src/jsMain/resources/index.html
we are building skiko with 1.5.10 while sample was build against 1.5.21 - this lead to IR incompatibility in js sample so this small fix is for handling this issue (plus introducing html file to link static and start working on js target to foll extent)
=> Js resources corrected

skiko/build.gradle.kts
Thus, getting rid of sed extermal call
=> Postprocess skiko.js file directly while adding to the jar

skiko/src/commonMain/kotlin/org/jetbrains/skia/Bitmap.kt, skiko/src/commonMain/kotlin/org/jetbrains/skia/Canvas.kt, skiko/src/commonMain/kotlin/org/jetbrains/skia/ColorFilter.kt, skiko/src/commonMain/kotlin/org/jetbrains/skia/Data.kt, skiko/src/commonMain/kotlin/org/jetbrains/skia/Drawable.kt, skiko/src/commonMain/kotlin/org/jetbrains/skia/Image.kt, skiko/src/commonMain/kotlin/org/jetbrains/skia/ImageFilter.kt, skiko/src/commonMain/kotlin/org/jetbrains/skia/MaskFilter.kt, skiko/src/commonMain/kotlin/org/jetbrains/skia/Path.kt, skiko/src/commonMain/kotlin/org/jetbrains/skia/PathEffect.kt, skiko/src/commonMain/kotlin/org/jetbrains/skia/Picture.kt, skiko/src/commonMain/kotlin/org/jetbrains/skia/Region.kt, skiko/src/commonMain/kotlin/org/jetbrains/skia/Shader.kt, skiko/src/commonMain/kotlin/org/jetbrains/skia/TextBlob.kt, skiko/src/commonMain/kotlin/org/jetbrains/skia/TextBlobBuilder.kt, skiko/src/commonMain/kotlin/org/jetbrains/skia/impl/Native.kt, skiko/src/jsMain/kotlin/org/jetbrains/skia/impl/Native.js.kt, skiko/src/jvmMain/kotlin/org/jetbrains/skia/impl/Native.jvm.kt, skiko/src/nativeMain/kotlin/org/jetbrains/skia/impl/Native.native.kt
but excluding functions returning non-primitive types
=> interopScope {} for all functions receiving primitive arrays

skiko/src/commonMain/cpp/generated/PathSegmentIterator.cc, skiko/src/commonMain/kotlin/org/jetbrains/skia/Path.kt, skiko/src/commonMain/kotlin/org/jetbrains/skia/PathSegmentIterator.kt, skiko/src/commonTest/kotlin/org/jetbrains/skia/PathTests.kt, skiko/src/commonTest/kotlin/org/jetbrains/skia/util/assertCloseEnough.kt, skiko/src/commonTest/kotlin/org/jetbrains/skia/util/makeFromResource.kt, skiko/src/jvmMain/cpp/common/PathSegmentIterator.cc, skiko/src/jvmTest/kotlin/org/jetbrains/skiko/FontMgrTest.kt, skiko/src/jvmTest/kotlin/org/jetbrains/skiko/PathMeasureTest.kt, skiko/src/jvmTest/kotlin/org/jetbrains/skiko/PathTest.kt, skiko/src/jvmTest/kotlin/org/jetbrains/skiko/TestLineTest.kt, skiko/src/jvmTest/kotlin/org/jetbrains/skiko/TypefaceTest.kt, skiko/src/jvmTest/kotlin/org/jetbrains/skiko/paragraph/FontCollectionTest.kt
This is an example of how I intended to deal with commonization - if we are fine with this I will in very fast fashion do the rest in exactly same fashion.
=> An example of commonized entity

skiko/src/jsMain/kotlin/org/jetbrains/skia/impl/Native.js.kt
This produces slightly better code but most importantly is a bit easier to test and less error-prone.
=> Don't use js function anywhere in interop

skiko/src/commonMain/kotlin/org/jetbrains/skia/Canvas.kt, skiko/src/commonMain/kotlin/org/jetbrains/skia/Matrix44.kt, skiko/src/commonTest/kotlin/org/jetbrains/skia/CanvasTest.kt, skiko/src/jvmMain/cpp/common/Canvas.cc, skiko/src/nativeJsMain/cpp/Canvas.cc
`org_jetbrains_skia_Canvas__1nDrawDrawable` was left unimplemented until Drawable is ready
=> add Canvas methods implementations for nativeJsMain

skiko/src/commonMain/kotlin/org/jetbrains/skia/FontFeature.kt, skiko/src/commonMain/kotlin/org/jetbrains/skia/paragraph/TextStyle.kt, skiko/src/jvmMain/cpp/common/interop.cc, skiko/src/jvmMain/cpp/common/interop.hh, skiko/src/jvmMain/cpp/common/paragraph/TextStyle.cc, skiko/src/nativeJsMain/cpp/common.h, skiko/src/nativeJsMain/cpp/common_interop.cc, skiko/src/nativeJsMain/cpp/paragraph/TextStyle.cc
- Long replaced by UInt
- toInterop serializes FontFeature as 4 ints
- fromInterop deserializes FontFeature from 2 ints 
the difference between toInterop and fromInterop (4 ints vs 2 ints) caused by different types in skia.
=> Add toInterop for FontFeature.kt and update bindings accordingly

skiko/src/commonMain/kotlin/org/jetbrains/skia/PathEffect.kt, skiko/src/commonTest/kotlin/org/jetbrains/skia/PathEffectTest.kt, skiko/src/jvmMain/cpp/common/PathEffect.cc, skiko/src/nativeJsMain/cpp/PathEffect.cc
=> Implement PathEffect native methods

skiko/src/jvmMain/cpp/common/Typeface.cc, skiko/src/nativeJsMain/cpp/Typeface.cc
Remove workaround for https://bugs.chromium.org/p/skia/issues/detail?id=10929
=> Remove no longer needed workaround

skiko/src/commonMain/kotlin/org/jetbrains/skia/paragraph/StrutStyle.kt, skiko/src/commonTest/kotlin/org/jetbrains/skia/StrutStyleTests.kt, skiko/src/jvmMain/cpp/common/paragraph/StrutStyle.cc, skiko/src/nativeJsMain/cpp/paragraph/StrutStyle.cc
Commonize setting fontStyle in StrutStyle and introduce appropriate Test
=> Commonize setting fontStyle in StrutStyle

skiko/src/commonTest/kotlin/org/jetbrains/skia/DataTest.kt, skiko/src/commonTest/kotlin/org/jetbrains/skia/TextBlobTest.kt
=> clean up debug prints in tests

skiko/build.gradle.kts, skiko/buildSrc/src/main/kotlin/properties.kt, skiko/ci/build.gradle.kts
Also, add `-` between OS and Arch in native artifacts ids
=> Republish native artifacts to Maven Central

skiko/build.gradle.kts
Also move -std=c++17 to skiaPreprocessorFlags
=> Add buildType compiler flags for native bridges & wasm

skiko/src/commonMain/kotlin/org/jetbrains/skia/Canvas.kt, skiko/src/commonMain/kotlin/org/jetbrains/skia/Font.kt, skiko/src/commonMain/kotlin/org/jetbrains/skia/ManagedString.kt, skiko/src/commonMain/kotlin/org/jetbrains/skia/paragraph/Paragraph.kt, skiko/src/nativeJsMain/cpp/paragraph/Paragraph.cc
Helps with https://github.com/JetBrains/skiko/issues/431
=> Fix few signature inconsistencies

.github/workflows/blank.yml, README.md
- Add ':SkiaJvmSample:installDist' to bash scripts on GitHub Actions.
- Simplify in some script 'cd ./skiko' with gradle feature for includedBuilds (https://docs.gradle.org/current/userguide/composite_builds.html#interacting_with_composite_builds).  
- Add README.md note - how to run jvm sample.
=> check SkiaJvmSample on pull_request

samples/SkiaJsSample/src/jsMain/kotlin/org/jetbrains/skiko/sample/js/App.kt, samples/SkiaJsSample/src/jsMain/kotlin/org/jetbrains/skiko/sample/js/BouncingBalls.kt
It seems APIs are changed and the sample needs to be updated.
=> Fix SkiaJsSample build failed

samples/SkiaMultiplatformSample/src/commonMain/kotlin/org/jetbrains/skiko/sample/Clocks.kt, skiko/.run/test.run.xml, skiko/src/awtMain/kotlin/org/jetbrains/skiko/Convertors.jvm.kt, skiko/src/awtMain/kotlin/org/jetbrains/skiko/SkiaLayer.awt.kt, skiko/src/awtMain/kotlin/org/jetbrains/skiko/SkikoKey.awt.kt, skiko/src/commonMain/kotlin/org/jetbrains/skiko/Events.kt, skiko/src/commonMain/kotlin/org/jetbrains/skiko/SkikoView.kt, skiko/src/iosMain/kotlin/org/jetbrains/skiko/Convertors.ios.kt, skiko/src/iosMain/kotlin/org/jetbrains/skiko/SkiaLayer.ios.kt, skiko/src/iosMain/kotlin/org/jetbrains/skiko/SkikoViewController.kt, skiko/src/jsMain/kotlin/org/jetbrains/skiko/Convertors.js.kt, skiko/src/jsMain/kotlin/org/jetbrains/skiko/SkiaLayer.js.kt, skiko/src/linuxMain/kotlin/org/jetbrains/skiko/SkiaLayer.linux.kt, skiko/src/macosMain/kotlin/org/jetbrains/skiko/Convertors.macos.kt, skiko/src/macosMain/kotlin/org/jetbrains/skiko/SkiaLayer.macos.kt
- added raw touch events for [uikit]
- added key code and modifiers in [SkikoInputEvent]
- added event [timestamp]
- added delta's to scroll event
=> Further commonization of skiko events.

samples/SkiaMultiplatformSample/src/iosMain/kotlin/org/jetbrains/skiko/sample/App.ios.kt, skiko/src/iosMain/kotlin/org/jetbrains/skiko/SkiaLayer.ios.kt, skiko/src/iosMain/kotlin/org/jetbrains/skiko/SkikoViewController.kt
- Refactored [SkikoUIViewController]
- Added [SkikoUIView] for use in compose
Note: to show/hide screen keyboard on simulator you must unset option: I/O -> Keyboard -> Connect Hardware Keyboard
=> Added support to show/hide screen keyboard. 

skiko/src/jsMain/kotlin/org/jetbrains/skiko/Convertors.js.kt, skiko/src/jsMain/kotlin/org/jetbrains/skiko/SkiaLayer.js.kt, skiko/src/macosMain/kotlin/org/jetbrains/skiko/SkiaLayer.macos.kt
This is proof of concept and I'm creating PR just so that it would be easier to inspect it
=> JS Input event

skiko/src/awtMain/kotlin/org/jetbrains/skiko/context/DirectSoftwareContextHandler.kt, skiko/src/awtMain/kotlin/org/jetbrains/skiko/context/MetalContextHandler.kt, skiko/src/iosMain/kotlin/org/jetbrains/skiko/context/MetalContextHandler.kt, skiko/src/jvmTest/kotlin/org/jetbrains/skiko/SkiaLayerTest.kt, skiko/src/macosMain/kotlin/org/jetbrains/skiko/context/MetalContextHandler.macos.kt
Fixes https://github.com/JetBrains/compose-jb/issues/1852
=> Fix rendering of an empty layer on metal

skiko/src/commonMain/kotlin/org/jetbrains/skia/ImageFilter.kt, skiko/src/commonMain/kotlin/org/jetbrains/skia/RuntimeShaderBuilder.kt, skiko/src/commonTest/kotlin/org/jetbrains/skia/ImageFilterTest.kt, skiko/src/jvmMain/cpp/common/ImageFilter.cc, skiko/src/jvmMain/cpp/common/RuntimeShaderBuilder.cc, skiko/src/nativeJsMain/cpp/ImageFilter.cc, skiko/src/nativeJsMain/cpp/RuntimeShaderBuilder.cc
For https://github.com/JetBrains/skiko/issues/519
See sample code and screenshot at https://github.com/JetBrains/skiko/issues/519
=> Add bindings for SkImageFilters::RuntimeShader

skiko/src/nativeJsMain/cpp/paragraph/LineMetrics.cc
Changed the confused types in LineMetrics mapping
=> fix nativeJsMain LineMetrics mapping

skiko/build.gradle.kts, skiko/buildSrc/src/main/kotlin/properties.kt
Now we can see an agent build path on the place of dylib id and version set to 0.0.0
=> Set proper dylib id and version

skiko/src/commonMain/kotlin/org/jetbrains/skia/shaper/Shaper.kt, skiko/src/jvmMain/cpp/common/Font.cc
=> Fix segfaults

skiko/buildSrc/src/main/kotlin/properties.kt, skiko/src/jvmMain/cpp/common/stubs.cc
Recently it was added to CI, and wasn't properly tested
=> Fix debug build

skiko/src/commonMain/cpp/common/shaper/FontRunIterator.cc
Sometimes our tests susperiously hangs on linux.
It's attempt to fix it
[trace.txt](https://github.com/JetBrains/skiko/files/9470221/trace.txt)
=> Fix hang in text shaping

skiko/src/awtMain/kotlin/org/jetbrains/skiko/redrawer/Direct3DRedrawer.kt
Fixes https://github.com/JetBrains/skiko/issues/582
=> Fix crash on Windows when there is no compatible DirectX adapter

samples/SkiaMultiplatformSample/src/awtMain/kotlin/org/jetbrains/skiko/sample/App.awt.kt, samples/SkiaMultiplatformSample/src/awtMain/kotlin/org/jetbrains/skiko/sample/AwtClocks.kt, samples/SkiaMultiplatformSample/src/commonMain/kotlin/org/jetbrains/skiko/sample/Clocks.kt, samples/SkiaMultiplatformSample/src/iosMain/kotlin/org/jetbrains/skiko/sample/IosClocks.kt, samples/SkiaMultiplatformSample/src/iosMain/kotlin/org/jetbrains/skiko/sample/getSkikoViewContoller.kt, samples/SkiaMultiplatformSample/src/jsMain/kotlin/org/jetbrains/skiko/sample/App.js.kt, samples/SkiaMultiplatformSample/src/jsMain/kotlin/org/jetbrains/skiko/sample/JsClocks.kt, samples/SkiaMultiplatformSample/src/macosMain/kotlin/org/jetbrains/skiko/sample/App.macos.kt, samples/SkiaMultiplatformSample/src/macosMain/kotlin/org/jetbrains/skiko/sample/MacOsClocks.kt, samples/SkiaMultiplatformSample/src/macosMain/kotlin/org/jetbrains/skiko/sample/MacosClocks.kt, skiko/src/iosMain/kotlin/org/jetbrains/skiko/SkikoUIView.kt
After changing input, some samples became broken. (iOS and JS)
Fixed it!
Also, found and fixed NPE bug in iOS text input.
=> Fix text input in samples

skiko/src/jvmMain/kotlin/org/jetbrains/skiko/SkikoProperties.kt
Minor refactoring for a property getter.
=> Simplify an `if` expression

skiko/build.gradle.kts
Some unexpected changes in build.gradle.kts were required to make it work.
=> Update kotlin to 1.7.20

samples/SkiaMultiplatformSample/src/iosMain/kotlin/org/jetbrains/skiko/sample/getSkikoViewContoller.kt, skiko/src/iosMain/kotlin/org/jetbrains/skiko/SkikoUIView.kt
Add keyboard customisation variables on iOS to be used in compose-jb
=> Add keyboard customisation (iOS)

samples/SkiaMultiplatformSample/build.gradle.kts
Update needs to correct compilation on iOS
=> MPP sample, kotlin 1.7.20

DEVELOPMENT.md
Specified a more detailed manual how to install Visual Studio. I checked it on a clean PC.
=> Update docs about development on Windows

skiko/src/jsMain/kotlin/org/jetbrains/skia/impl/Native.js.kt, skiko/src/jsWasmMain/kotlin/org/jetbrains/skia/impl/Native.js.kt, skiko/src/nativeJsMain/cpp/common_interop.cc, skiko/src/wasmMain/kotlin/org/jetbrains/skia/impl/Native.wasm.kt
Direct (no JS layer) for kotlin.wasm to skiko interop
=> Fast skiko.wasm to skia arrays and string interop

skiko/src/androidMain/kotlin/org/jetbrains/skiko/Convertors.android.kt, skiko/src/androidMain/kotlin/org/jetbrains/skiko/Renderer.android.kt, skiko/src/androidMain/kotlin/org/jetbrains/skiko/SkiaLayer.android.kt, skiko/src/awtMain/kotlin/org/jetbrains/skiko/SkiaLayer.awt.kt, skiko/src/commonMain/kotlin/org/jetbrains/skiko/Events.kt, skiko/src/commonMain/kotlin/org/jetbrains/skiko/SkikoView.kt, skiko/src/iosMain/kotlin/org/jetbrains/skiko/SkiaLayer.ios.kt, skiko/src/iosMain/kotlin/org/jetbrains/skiko/SkikoUIView.kt, skiko/src/jsMain/kotlin/org/jetbrains/skiko/SkiaLayer.js.kt, skiko/src/linuxMain/kotlin/org/jetbrains/skiko/SkiaLayer.linux.kt, skiko/src/macosMain/kotlin/org/jetbrains/skiko/SkiaLayer.macos.kt
1. Remove SkikoTouchEvent, we send all pointer events as SkikoPointerEvent now.
2. Add SkikoPointerEvent.Pointer that represents a separate touch/mouse
3. Implement multitouch for iOS/Android
=> Implement multitouch

skiko/src/iosMain/kotlin/org/jetbrains/skiko/SkikoUIView.kt
=> fix iOS pointer event timestamp

skiko/src/awtMain/kotlin/org/jetbrains/skiko/SkiaLayer.awt.kt
This is an improvement in general, but specifically with the fix from [JBR-5274](https://youtrack.jetbrains.com/issue/JBR-5274) in mind. Previously, we didn't pay attention to actual updates that did come in and we didn't update our remembered value from there. Especially since those updates come in reliably on macOS now when the display scaling changes (as soon as the change lands in our JBR builds), we would accidentally duplicate `graphicsContextScaleTransform` updates. With these changes, it should again only fire if such an update was missing.
=> Avoid duplicated scale transform updates

skiko/src/jsMain/kotlin/org/jetbrains/skiko/Actuals.js.kt
This code does not work correctly. Revert it back.
=> Revert "Implement ClipboardManager_getText for js (#690)"

skiko/src/awtMain/kotlin/org/jetbrains/skiko/context/MetalContextHandler.kt, skiko/src/awtMain/kotlin/org/jetbrains/skiko/redrawer/MetalRedrawer.kt, skiko/src/awtMain/objectiveC/macos/MetalContextHandler.mm, skiko/src/awtMain/objectiveC/macos/MetalDevice.h, skiko/src/awtMain/objectiveC/macos/MetalRedrawer.mm
During Metal investigation, I decided to make small refactorings, so I understand code more. I hope that it also makes it more easier to read
Refactorings include:
* Moving of some native code from Redrawer to ContextHandler, since it is needed only there. And before "back" reference was used. Now ContextHandler is kinda separate class
* Provided simple k docs they can be improved later. I think I'll write more during later investigation
=> Refactor awt metal code and provide some basic docs

skiko/build.gradle.kts
=> Bump min iOS to 12 - required to build with Xcode 14.3

skiko/build.gradle.kts, skiko/src/macosMain/kotlin/org/jetbrains/skiko/SkiaLayer.macos.kt
Note the workaround for override was removed.
=> Update kotlin version - 1.8.20

skiko/src/iosMain/kotlin/org/jetbrains/skiko/SkikoUIView.kt
Issue: https://github.com/JetBrains/compose-multiplatform/issues/3276
=> fix iOS TextField Context menu blink bug

samples/SkiaAndroidSample/.gitignore, samples/SkiaAndroidSample/src/main/java/org/jetbrains/skiko/sample/Clocks.kt, samples/SkiaMultiplatformSample/src/commonMain/kotlin/org/jetbrains/skiko/sample/Clocks.kt
Fixes after removing `fun onTouchEvent(events: Array<SkikoTouchEvent>)` in this PR: https://github.com/JetBrains/skiko/pull/725
=> Fix SkiaMultiplatformSample and SkiaAndroidSample

samples/SkiaMultiplatformSample/build.gradle.kts
Fix compilation of iOS part in SkiaMultiplatformSample.
Just updated to Kotlin 1.8.20
=> fix iOS sample

skiko/src/iosMain/kotlin/org/jetbrains/skiko/redrawer/MetalRedrawer.ios.kt
Similar to https://github.com/JetBrains/skiko/pull/754, but on iOS
=> Add overcommitment prevention mechanism (iOS)

skiko/src/iosMain/kotlin/org/jetbrains/skiko/SkikoUIView.kt
Send touches in view own coordinate space
Prerequisite for:
https://github.com/JetBrains/compose-multiplatform-core/pull/679
=> Change sent touches coordinate space to SkikoUIView space

skiko/build.gradle.kts
=> Publish linker opts for mac os linking

skiko/build.gradle.kts, skiko/src/awtMain/cpp/linux/swingRedrawer.cc, skiko/src/awtMain/kotlin/org/jetbrains/skiko/swing/LinuxOpenGLSwingRedrawer.kt, skiko/src/awtMain/kotlin/org/jetbrains/skiko/swing/SwingRedrawer.kt
This PR provides offscreen rendering on Graphics with GPU acceleration for Linux using OpenGL
There is still room for improvement from the performance side, like we can reuse created textures and so on. But performance is comparable with Metal (Intel) on my Intel laptop
=> Introduce Swing interop with offscreen rendering on Linux with OpenGL

skiko/src/iosMain/kotlin/org/jetbrains/skiko/redrawer/MetalRedrawer.ios.kt
Adhere to [the Apple recommended practices](https://developer.apple.com/documentation/metal/gpu_devices_and_work_submission/preparing_your_metal_app_to_run_in_the_background?language=objc).
=> Restrict redrawing when the application is background.

skiko/src/awtMain/kotlin/org/jetbrains/skiko/Accessibility.kt, skiko/src/awtMain/kotlin/org/jetbrains/skiko/HardwareLayer.kt, skiko/src/awtMain/kotlin/org/jetbrains/skiko/MetalApi.kt, skiko/src/awtMain/objectiveC/macos/Accessibility.mm, skiko/src/awtMain/objectiveC/macos/MetalApi.mm, skiko/src/awtTest/kotlin/org/jetbrains/skiko/AccessibilityKtTest.kt
Introduce nativeInitializeAccessible method that should be called on Accessible creation. Read doc for this function for details and see releated [issue](https://youtrack.jetbrains.com/issue/COMPOSE-176) for details
=> Accessibility focus on wrong component fix

skiko/src/awtMain/kotlin/org/jetbrains/skiko/Actuals.awt.kt
Fixes https://github.com/JetBrains/compose-multiplatform/issues/3583
=> Use xdg-open to open URLs on Linux if AWT does not support it

skiko/docker/linux-emscripten-amd64/Dockerfile
This change is necessary to build skiko after this PR(https://github.com/JetBrains/skiko/pull/831) on teamcity
=> Update emcc version in linux-emscripten-amd64 Docker

skiko/src/awtMain/cpp/linux/theme.cc, skiko/src/awtMain/cpp/windows/drawlayer.cc, skiko/src/awtMain/kotlin/org/jetbrains/skiko/SystemTheme.awt.kt, skiko/src/awtMain/objectiveC/macos/Drawlayer.mm
=> Fix library load on `SystemTheme`

skiko/src/commonMain/kotlin/org/jetbrains/skia/Image.kt, skiko/src/darwinMain/kotlin/org/jetbrains/skia/Image.darwin.kt, skiko/src/darwinTest/kotlin/org/jetbrains/skia/ImageTest.darwin.kt
API change: New public function for all darwin target
=> Add `fun Image.Companion.makeFromEncoded(nsData: NSData): Image`

skiko/src/awtMain/cpp/windows/directXRedrawer.cc
It adds a fallback to the old initialization method in case of any problems.
=> Add fallback to `CreateSwapChainForHwnd`

skiko/src/awtMain/kotlin/org/jetbrains/skiko/RenderExceptionsHandler.kt
=> log render exception via logger interface, check that path

skiko/src/awtMain/kotlin/org/jetbrains/skiko/SkiaLayer.awt.kt
=> Allow paint before showing

skiko/build.gradle.kts, skiko/buildSrc/src/main/kotlin/SkikoProjectContext.kt, skiko/buildSrc/src/main/kotlin/properties.kt
This commit is first step in set of actions we need to take to build skia-package via gradle in the skiko repository
However it makes sense on it's own as well.
=> Split skia download/unzipping task creation and invocation

skiko/buildSrc/src/main/kotlin/tasks/configuration/JvmTasksConfiguration.kt
See https://github.com/JetBrains/skiko/issues/973
=> fix #973 -- NumberFormatException in JvmTaskConfiguration

skiko/src/commonMain/kotlin/org/jetbrains/skia/RuntimeShaderBuilder.kt, skiko/src/commonTest/kotlin/org/jetbrains/skia/RuntimeShaderBuilderTest.kt, skiko/src/jvmMain/cpp/common/RuntimeShaderBuilder.cc, skiko/src/nativeJsMain/cpp/RuntimeShaderBuilder.cc
https://github.com/JetBrains/skiko/issues/947 support passing a `FloatArray` to the shader
=> RuntimeShaderBuilder uniform float array api

skiko/src/awtMain/kotlin/org/jetbrains/skiko/redrawer/AWTRedrawer.kt, skiko/src/commonMain/kotlin/org/jetbrains/skiko/SkiaLayerAnalytics.kt
Fixes https://youtrack.jetbrains.com/issue/SKIKO-994/Add-logging-for-rendering
=> SkiaLayerAnalytics. Rendering logging

skiko/src/commonMain/cpp/common/include/node/RenderNode.h, skiko/src/commonMain/cpp/common/node/RenderNode.cpp, skiko/src/commonMain/kotlin/org/jetbrains/skiko/node/RenderNode.kt, skiko/src/jvmMain/cpp/common/node/RenderNode.jvm.cpp, skiko/src/nativeJsMain/cpp/node/RenderNode.native.cpp
Required to fix https://youtrack.jetbrains.com/issue/CMP-7508
Test: covered by existing tests
=> Add clip mode and anti-alias options to RenderNode

skiko/settings.gradle.kts
Fixes https://youtrack.jetbrains.com/issue/CMP-7603/Fix-Maven-Central-publication for Skiko
Just a quick fix that adds an updated library.
For a proper fix I created an issue https://youtrack.jetbrains.com/issue/SKIKO-1003/Unify-Maven-publication-of-Skiko-with-Compose
=> Fix Maven Central publication

skiko/gradle.properties
see https://youtrack.jetbrains.com/issue/CMP-7630
=> Update skia dependency from m132-9b3c42e2f9-2 to m132-9b3c42e2f9-3

skiko/docker/linux-emscripten-amd64/Dockerfile
emscripten 3.1.50 supports mimalloc - https://github.com/emscripten-core/emscripten/blob/main/ChangeLog.md#3150---112923 
We want to try it.
=> Update emscripten version in docker

skiko/docker/linux-amd64/Dockerfile
https://github.com/JetBrains/skiko/pull/1051#discussion_r2107305732
=> Update linux-amd64/Dockerfile with dependencies needed for cross compiling linuxArm64 target

samples/SkiaAwtSample/build.gradle.kts, samples/SkiaMultiplatformSample/build.gradle.kts
=> update passing jvmArgs in samples to the latest Gradle

skiko/build-with-local-skia.sh, skiko/gradle.properties, skiko/src/commonMain/cpp/common/node/RenderNode.cpp, skiko/src/commonTest/kotlin/org/jetbrains/skiko/node/RenderNodeTest.kt
Fixes [CMP-8701](https://youtrack.jetbrains.com/issue/CMP-8701)
Addition to https://github.com/JetBrains/skia/pull/11
=> Use proper `bbhFactory` in `onMakePictureSnapshot`

.github/workflows/ci.yml
Restoring correct behaviour of caches after #1108
=> Remove unused software instead of cleaning caches
